### ISSUE TITLE
Moq parameter injected method?

### ISSUE THREAD

**Issue by SWarnberg** [moq/moq4#1016]
Probably a stupid question, but want to make sure.

I'm creating an object where all constructor injected parameters are mocked. Then, internally, the method under test is executing a method that has another parameter injected service. Is it possible to use Moq and have this parameter use the mocked object?

**Comment by stakx** [comment]
> internally, the method under test is executing a method that has another parameter injected service.

Which means that the method under test is the party that injects a service into that other method, right?

I'm trying to piece together from your description above what your code might look like. I am assuming something like this (which doesn't make complete sense):

```csharp
var component = new Component(Mock.Of<IService1>(), Mock.Of<IService2>(), Mock.Of<IService3>());

class Component
{
    public Service(IService1 s1, IService s2, IService s3)
    {
        ...
    }

    public /* ? */ void MethodUnderTest()
    {
        var s4 = GetFromSomewhere<IService4>();
        SomeOtherMethod(s4);
    }

    private /* ? */ void SomeOtherMethod(IService4 d4)
    {
        ...
    }
}
```

> Is it possible to use Moq and have this parameter use the mocked object?

If the above assumptions are correct, you'd either have to (1) be able to determine from the outside which service the method under test is going to inject into that other method (and provide a mocked object for it), or (2) provide an alternative implementation for the method under test using `.Callback`. This only works if the method under test is `virtual` and non-`sealed`, and if that other method is accessible from the outside so that it can be called from the callback.

So in the above example, you'd have to make the following changes:

```diff
-var component = new Component(Mock.Of<IService1>(), Mock.Of<IService2>(), Mock.Of<IService3>());
+var componentMock = new Mock<Component>(Mock.Of<IService1>(), Mock.Of<IService2>(), Mock.Of<IService3>());
+var component = componentMock.Object;
+var injectedService4 = Mock.Of<IService4>();

+componentMock.Setup(m => m.MethodUnderTest())
+             .Callback(() => component.SomeOtherMethod(injectedService4));

 // or:

+componentMock.Setup(m => m.GetFromSomewhere<IService4>())
+             .Returns(injectedService4);

 class Component
 {
     ...

-    public /* ? */ void MethodUnderTest()
+    public virtual void MethodUnderTest()
     {
         var s4 = GetFromSomewhere<IService4>();
         SomeOtherMethod(s4);
     }

-    private /* ? */ void SomeOtherMethod(IService4 d4)
+    public void SomeOtherMethod(IService4 d4)
     {
         ...
     }
 }

**Comment by stakx** [comment]
@SWarnberg, does this answer your question?

**Comment by SWarnberg** [comment]
@stakx, yes, with some modification it did. Thanks.
