### ISSUE TITLE
Allow chaining of Setup().Returns() 

### ISSUE THREAD

**Issue by jkodroff** [moq/moq4#103]
I'd love to be able to do this:

```
mock
  .Setup(x => x.Method1())
  .Returns(value1)
  .Setup(x => x.Method2())
  .Returns(value2);
```

Any reason we wouldn't want to add this feature?  If it's cool, I'll create the PR.

**Comment by stakx** [comment]
I can see two problems with this:

* It makes the boundary between one setup and the next more difficult to see. Indentation will have to do the work of a statement terminator, so to speak.

* This would potentially require a lot of added `.Setup` methods in the fluent interface API so that you're able to start a new setup after any method.

In contrast, what you're asking for is only going to save you 5 characters (`mock` and a `;`).

Given the rather small potential savings of this feature, I do not think it is worth the work to enable it. :-/

Have you looked into `Mock.Of<>`? `Mock.Of<IX>(x => x.Method1() == value1 && x.Method2() == value2)` is even more succinct that what you suggested above.
