### ISSUE TITLE
Feature request: enable verification of extension-methods calls

### ISSUE THREAD

**Issue by weitzhandler** [moq/moq4#1045]
Hi,

I often come across mocks that expose complex methods with multiple complex parameters of lambdas etc.
Those methods are provided with companion methods that enable passing just one or two primitive-type arguments delegate them to the actual complex method.

Let's use the [`Microsoft.Extensions.Logging.ILogger.Log`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger.log?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Logging_ILogger_Log__1_Microsoft_Extensions_Logging_LogLevel_Microsoft_Extensions_Logging_EventId___0_System_Exception_System_Func___0_System_Exception_System_String__) method as an example. It has the following signature:

```c#
public void Log<TState>(
  LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);
```

Pretty complex, but in essence you would almost never call it directly and would instead call the various extension methods in [`LoggerExtensions`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions?view=dotnet-plat-ext-3.1).

I wonder how hard it could be enabling verification through extension methods.

One way could be (and I'm sure there would be other, better, ideas), when calling [`LogWarning`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.logwarning?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Logging_LoggerExtensions_LogWarning_Microsoft_Extensions_Logging_ILogger_System_String_System_Object___) (`LogWarning (this ILogger logger, string message, params object[] args);`, could we internally prepare a verification expectation by recording what's being called downstream on a similar dummy mock, so that we could then verify it was called on the actual mock?

That would enable us to write 

```c#
loggerMock
  .Verify(logger => logger.LogWarning("Error occurred"), Times.Once);
```

which is what we actually want to verify, instead of the one that's so tedious and taking so long to figure out and make it work

```c#
public static void VerifyLog<TCategoryName>(this Mock<ILogger<TCategoryName>> loggerMock, LogLevel logLevel, string expectedMessage)
{
  loggerMock.Verify(logger =>
    logger.Log(
      logLevel,
      It.IsAny<EventId>(),
      It.Is<It.IsAnyType>((state, type) => state.ToString() == expectedMessage),
      It.IsAny<Exception>(),
      It.Is<Func<It.IsAnyType, Exception, string>>((func, type) => true)), //IsAny doesn't work
    Times.Once);
}
```

I'm willing to contribute.

**Comment by stakx** [comment]
> I wonder how hard it could be enabling verification through extension methods.

Impossible, unless you use the CLR's unmanaged Profiling API, but then you sacrifice portability (think Mono) so that's currently a no-go.

> could we internally prepare a verification expectation by recording what's being called downstream on a similar dummy mock,

That's very similar to how expression reconstruction works for `SetupSet`/`VerifySet`: those are given a delegate, which gets executed on a dummy mock. The virtual, overridable methods invoked on the dummy mock are recorded, amd from that a LINQ expression tree gets reconstructed.

That approach has several downsides, basically it only works correctly under very specific conditions. If we used that approach to support extension methods, we'd have to assume that extension methods deterministically call exactly one virtual, overridable method on the `this` argument. If the extension method calls none, or more than 1 such method, or if it calls different methods depending on its input, you're going to see some weird behavior.

IMHO it's best not to go there... this will complicate Moq internals quite a bit, make Moq's LINQ expression tree handling less precise, and it'll be a fragile feature at best. As such is begging for support questions and false bug reports.

**Comment by weitzhandler** [comment]
Your kind and comprehensive answer makes a lot of sense.
Thanks for taking the time to write it.

**Comment by weitzhandler** [comment]
Why doesn't this work:

```c#
It.IsAny<Func<It.IsAnyType, Exception, string>>()
```

Whereas this one does?

```c#
It.Is<Func<It.IsAnyType, Exception, string>>((func, type) => true))
```
