### ISSUE TITLE
Moq seems to potentially be reporting awaited async calls incorrectly in Verify

### ISSUE THREAD

**Issue by illegalnumbers** [moq/moq4#1052]
See the code below for an example. Using moq 4.14.5, xunit 2.4.1, xunit.runner.visualstudio 2.4.3 and Microsoft.NET.Test.Sdk 16.7.1. The behavior that I'm seeing is when you make an expectation on a method call that is async and the call is awaited and then later you modify a parameter to that original async call Moq reports that your verification has failed because the object is not equal to the original value that was submitted to the `await`ed call.

```
using System;
using System.Threading;
using System.Threading.Tasks;
using Moq;
using Xunit;

namespace ConsoleApp1
{
    class Program
    {
        public async void Main(IAsyncTest a)
        {
            Param p = new Param("test");
            Console.Out.WriteLine("First P value: " + p);
            await a.Attempt(p);
            p.x = "notTest";
            Console.Out.WriteLine("Second P value: " + p);
        }
    }

    public class Param
    {
        public string x { get; set; }

        public Param(string x)
        {
            this.x = x;
        }
        
        public override string ToString()
        {
            return this.x;
        }

        public override bool Equals(object? obj)
        {
            return this.x == ((Param) obj).x;
        }
    }

    public interface IAsyncTest
    {
        public Task<bool> Attempt(Param p);
    }
    
    class AsyncTest : IAsyncTest
    {
        public Task<bool> Attempt(Param p)
        {
            return Task.Factory.StartNew(() =>
            {
                Console.WriteLine(p.ToString());
                return true;
            });
        }
    }

    public class ProgramTest
    {
        [Fact]
        public void test()
        {
            Program p = new Program();
            p.Main(new AsyncTest());
            
            
            var moqAsync = new Mock<IAsyncTest>(MockBehavior.Loose);
            var param = new Param("test");
            Assert.Equal(param, new Param("test"));
            
            p.Main(moqAsync.Object);
            moqAsync.Verify(x => x.Attempt(param));
        }
    }
}
```

This program will output what I expect:
```
First P value: test
test
Second P value: notTest
First P value: test
Second P value: notTest
```

But then the expectation fails and the verify call states that the invocation performed was for the later value of `p.x`:
```
ConsoleApp1.ProgramTest.test

Moq.MockException : 
Expected invocation on the mock at least once, but was never performed: x => x.Attempt(test)

Performed invocations:

   Mock<IAsyncTest:1> (x):

      IAsyncTest.Attempt(notTest)

   at Moq.Mock.Verify(Mock mock, LambdaExpression expression, Times times, String failMessage)
   at Moq.Mock`1.Verify[TResult](Expression`1 expression)
   at ConsoleApp1.ProgramTest.test()
```

I would expect that the `Verify` call would see my awaited call and appropriately reflect that it had the right asserted parameter called with it.

**Comment by stakx** [comment]
We've had these kinds of reports several times. It boils down to this: `Param` is a `class`, that is, a reference type. So as Moq records invocations (along with their arguments), it will record _references_ to `Param` objects, not their values at the time of invocation. Because your `Program.Main` method changes `Param.x` from `"test"` to `"notTest"`, this will affect the recorded invocation, too. Your `Verify` fails because it expects to find an invocation with a `Param` having `x == "test"`; there would have been such an invocation at the beginning of `Program.Main` but not after it.

You may ask why we're not changing this seemingly counterintuitive behavior (as most people reporting similar cases have asked.) This is simply how reference & value types in .NET generally work. Changing it would require Moq making deep copies of every single argument on every single invocation, and that would be potentially prohibitively expensive, and also unnecessary most of the time.

Resolve this issue either by making `Param` a `struct` (value type) so `Param` values are copied instead of referenced; or use `Capture.In` along with a specialized, copying collection type to record `Param` values at the time of invocation.

**Comment by illegalnumbers** [comment]
Thanks for the explanation!
