### ISSUE TITLE
Unable to chain ReturnsAsync with Verifiable

### ISSUE THREAD

**Issue by blake-mealey** [moq/moq4#1057]
Hey, I am having some difficulty with one of my mocks. I want to do this:

```cs
var dbConnectionMock = new Mock<DbConnection>(MockBehavior.Loose);
dbConnectionMock.SetupDapperAsync(m =>
        m.QueryAsync(It.IsAny<string>(), It.IsAny<object>(), null, null, CommandType.StoredProcedure))
        .ReturnsAsync(new List<dynamic>()).Verifiable();
```

But when I do, I get NullReferenceException because somehow ReturnsAsync is returning null. I also can't do `.Verifiable().ReturnsAsync(...)` because `Verifiable` is `void`. (Note I am using the Moq.Dapper library here, but this seems unrelated to me since the method causing my issue is from the core library)

I have been able to get it working like this:

```cs
var dbConnectionMock = new Mock<DbConnection>(MockBehavior.Loose);
var mock = dbConnectionMock.SetupDapperAsync(m =>
        m.QueryAsync(It.IsAny<string>(), It.IsAny<object>(), null, null, CommandType.StoredProcedure));
mock.ReturnsAsync(new List<dynamic>());
mock.Verifiable();
```

But I'd rather not have to spread it out like that since usually the setup is chainable.

Any suggestions?

**Comment by stakx** [comment]
You definitely shouldn't have to spread out a setup like that. But it's hard to tell what's going wrong here since `SetupDapperAsync` isn't part of Moq. Can you please provide example repro code that _does not_ use any Moq extensions? (If you can only reproduce the problem using some 3rd-party extension library, you probably need to ask at their repository.)

**Comment by blake-mealey** [comment]
Sorry for the slow reply. I think you're right - it seems to be caused by the other library. I'll close this issue
