### ISSUE TITLE
Remove mandatory SetupAdd & SetupRemove for eventhandler subscription verification.

### ISSUE THREAD

**Issue by 80O** [moq/moq4#1058]
What is the reason that having to add this setup:
`_mock.SetupRemove(d => d.Event -= It.IsAny<EventHandler>());`

To verify this...
`_mock.VerifyRemove(d => d.Event -= It.IsAny<EventHandler>(), Times.Once);`

... is mandatory?

Normal function calls do not require to be 'registered' beforehand either. I think it will help if these setups are not required and act more like any other `Verify()` call.

**Comment by stakx** [comment]
IIRC, the reason was backward compatibility. `Verify{Add,Remove}` was added only recently (unlike `Setup{Add,Remove}` which has been around much longer). Those methods can only work iff event `+=` and `-=` are recorded in `mock.Invocations`, but previously this didn't happen, and that's why those verification methods weren't introduced for so long.

If we had simply started unconditionally recording `+=` and `-=`, that would have been a breaking change with respect to e.g. `VerifyNoOtherCalls`: existing code might have assumed that this call would succedd but now there might suddenly be additional invocations that weren't there before.

That's why we figured, if your test is _already_ aware of event (un-) subscriptions, it should be safe in that case to record them as invocations. And we chose the presence of the setup methods as the criterion whether yoir test is "aware of" event (un-) subscriptions.

Does this explanation make sense?

I agree this could be better, it was simply the safest thing to do at the time. It enabled additional verification with only a small risk of breaking existing code.
