### ISSUE TITLE
Setup().CallBase() - is this a bug or intended behavior?

### ISSUE THREAD

**Issue by replaysMike** [moq/moq4#1087]
Given the following class, I'm not seeing what I would expect to see using CallBase() based on whether children methods are virtual or not. I would expect to either see an exception if its not virtual, or to get the expected value.

```csharp
public class Helper
{
    public virtual int MethodA() 
        => VirtualMethod() + 1;

    public virtual int MethodB() 
        => NonVirtualMethod() + 1;

    public virtual int VirtualMethod() 
        => 123;

    public int NonVirtualMethod() 
        => 123;
}
```

```csharp
[TestFixture]
public class HelperTests
{
    [Test]
    public void Should_CallInto_Original()
    {
        var helperMock = new Mock<Helper>();
        helperMock.Setup(x => x.MethodA())
            .CallBase();
        helperMock.Setup(x => x.MethodB())
            .CallBase();

        var helper = helperMock.Object;
        var resultA = helper.MethodA(); // returns 1
        var resultB = helper.MethodB(); // returns 124

        Assert.AreEqual(resultA, 124); // should see 124, or an exception but instead 1 is returned
        Assert.AreEqual(resultB, 124);
    }
}
```

If the child method `VirtualMethod` being called into is virtual, it seems a blank implementation is overwriting the actual base implementation which would lead to really obscure bugs when virtual is removed. If the child method is not virtual you get the expected behavior. Is this really desired? That means `MethodA` has implementation that will be executed, but it's children will not.

**Comment by stakx** [comment]
@replaysMike there's not much more to say than what you already found out yourself.

Mocking classes is generally more difficult than mocking interfaces, because you have to take the base implementation into account. This can lead to tricky situations, as you discovered yourself.

When it comes to `mock.CallBase = true` and `setup.CallBase()`, perhaps it helps to ask yourself the following:

* Does (most of) the mocked class' behavior matter for the test? If so, setting `mock.CallBase = true` may be a good default. You can srill override the implementation using setups.

* Do you want the base implementation to be ignored? Then keep `mock.CallBase = false` and it will be "erased" as far as possible (overridable members). You can still counteract that erasure in certain places by using setups that specify `.CallBase()`.

So `mock.CallBase` lets you decide what you generally prefer re: base implementation, and setups provide for the exceptions.

You can also use strict mocks to discover whether the base implementation calls additional methods that you didn't anticipate in your setups.
