### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MarkPhillips** [moq/moq4#111]
Love your product.  Please clean up and elaborate on your product functionality within the documentation
.
Thanks

**Comment by stakx** [comment]
Hi @MarkPhillips, it has been a long time since you posted this. Are you still interested in following up on this issue?

If so, could you elaborate a little on your request? Do you have specific suggestions what about the documentation needs to be improved, and how?

I will close this issue in approx. 2 weeks' time, unless you reply back earlier. We can, however, always re-open the issue.
