### ISSUE TITLE
Mock.Of async expression

### ISSUE THREAD

**Issue by Astrophizz** [moq/moq4#139]
Maybe I'm doing it wrong but there doesn't seem to be a way to use the "Linq to Mocks" syntax for mocking async methods. Is it possible? If not, what would it take to make it possible?

**Comment by DaveVdE** [comment]
This worked for me:

```
var mock = Mock.Of<IService>(service => service.DoAsync() == Task.CompletedTask);
```

I suppose if you replace `Task.CompletedTask` with `Task.FromResult(something)` you can do it with just about everything.

**Comment by stakx** [comment]
I haven't thought much about this, but my gut feeling is that `Mock.Of` and `async` might not fit well together. If it were possible, it would be nice if you could do this:

```csharp
Mock.Of<IFoo>(async foo => await foo.GetAsync() == 42) 
```

Unfortunately, today's C# compiler cannot convert `async` lambdas to expression trees, so that's a major showstopper.

What we're left with is the ability to work directly with `Task` objects, like @DaveVdE mentioned above. For example:

```csharp
Mock.Of<IFoo>(foo => foo.GetAsync() == Task.FromResult(42) && foo.Bar = "Baz")
```

The gains here are pretty small. IMHO it would probably be better to just use `Mock.Of` for fairly straightforward setups and do more involved stuff with the fluent API (`new Mock<>().Setup().Returns()`).

**Comment by stakx** [comment]
Closing this for now, since there's nothing really that can be done. There's simply no way with today's .NET compilers to transform an async lambda to an expression tree.
