### ISSUE TITLE
Any reason there is no Mock.Of<>() overload with MockBehavior?

### ISSUE THREAD

**Issue by JohanLarsson** [moq/moq4#154]
```
public static T Of<T>(Expression<Func<T, bool>> predicate, MockBehavior behavior) where T : class
```

I think ^ could be useful but don't know if there is a reason it is not there. Hence this question.

**Comment by JohanLarsson** [comment]
Related question: Does mock.VerifyAll(); do anything if not strict? If not it should throw if called when not strict.

**Comment by kzu** [comment]
VerifyAll is unaffected by MockBehavior. It verifies that all setups have
been invoked.

It could be that in a loose mock you do want to verify certain setups. And
it could be that in a strict mock some setups were not invoked.

As to the previous question: the Linq provider ends up calling
SetupProperty on all the members used in the "query", so it couldn't be a
strict mock. BUT, I think that should be doable if the mock is initially
created as loose and later changed to strict internally, after the
expressions are evaluated...

Do you want to take a shot at a PR to fix that? That would be very helpful!

Thanks in advance


/kzu

Daniel Cazzulino | Team Lead | Xamarin for Visual Studio

**Comment by JohanLarsson** [comment]
Hopefully I can give it a try this weekend. Will update here if I give up or can't find time for it.
Thanks for a beautiful lib btw!

**Comment by kzu** [comment]
Keep us posted!

Thanks again for volunteering to look into this :)

/kzu from mobile
--

**Comment by JohanLarsson** [comment]
https://gitter.im/oxyplot/oxyplot
^ Gitter is pretty nice.

**Comment by stakx** [comment]
@JohanLarsson: Just a friendly ping. It's been a while since this thread was active. Did you ever get around to look into this? Do you still think this should be followed up at all?

**Comment by JohanLarsson** [comment]
I wrote a PR with it but there was a whitespace mess so it was never merged. Then I forgot about it many times. [Here](https://github.com/JohanLarsson/moq4/commit/3fecd86b83312b8f7de30bb5ef7122f3d561d457) is the diff, agreed it is messy.

**Comment by stakx** [comment]
OK, thanks for letting me know. This will probably be difficult to merge due to the diff's relative age. Nevertheless, I should eventually get around to taking a closer look at it. Once I do, I'll report back here.

**Comment by JohanLarsson** [comment]
I should clean it up. 

Adding `public static T Of<T>(MockBehavior behavior) where T : class` is trivial and does not need many tests.
I'll PR it tomorrow.

The overload `public static T Of<T>(MockBehavior behavior, Expression<Func<T, bool>> predicate) where T : class` is a bit trickier but the code & tests are already written.

**Comment by JohanLarsson** [comment]
Maybe there will not be a PR, I cloned it and tried building but it looked like a couple of hours of dev tool fighting. Is there a readme for how to build it?

![image](https://user-images.githubusercontent.com/1640096/27407386-60ac869a-56d8-11e7-8464-6b4db283055a.png)

![image](https://user-images.githubusercontent.com/1640096/27407407-72fa110a-56d8-11e7-9a38-e6b65f43f8e5.png)

![image](https://user-images.githubusercontent.com/1640096/27407429-84e7678c-56d8-11e7-91a9-29abe04f8ead.png)

Tried both Moq.sln & Moq.NetCore.sln, did just click build in VS.

**Comment by stakx** [comment]
This looks as if the NuGet package restore didn't kick in. You should be able to open either of the two solutions you mentioned. I am working on Moq in VS 2017, works fine.

**Comment by JohanLarsson** [comment]
Got it to build now, looks like having more than one package source confused nuget.exe.
Paket.exe is nice btw.

**Comment by stakx** [comment]
I closed the PR accompanying this issue a while ago, but overlooked the issue and left it open.

> Any reason there is no Mock.Of<>() overload with MockBehavior?

After looking into Moq's performance issues some more I've actually found one reason against this proposed additional overload: compared to `new Mock<T>()`, `Mock.Of<T>()` is super slow (slower by more than 1 order of magnitude) because it performs recursive property setups and some more work.

Given that the only time when you'd use the new `Mock.Of<T>(MockBehavior)` is to get a strict mock that isn't to be invoked (as you showed in the PR), all the additional work of setting up all properties is actually superfluous.

Thus adding this new overload at a time when the performance of `Mock.Of<T>()` hasn't yet been much improved would make it very easy for people to write inefficient (slow) tests.

The only real advantage here would be that `Mock.Of<T>(MockBehavior.Strict)` is a little neater than `new Mock<T>(MockBehavior.Strict).Object`, but that alone isn't worth the performance penalty IMO.

I suggest people who want that overload write their own utility method that returns a strict mocked object; adding this to Moq's main library at this time would be counterproductive.
