### ISSUE TITLE
Combine a subsequent setup with existing setup?

### ISSUE THREAD

**Issue by kappasims** [moq/moq4#158]
I have a set of tests for which I would like to define a common Returns on a mock dependency, but a unique per-test Callback. Since I have to call Setup again inside the test in order to get to Callback, the first Setup/Returns is completely overwritten. The only workaround for this I can think of is to maintain a reference to the ISetup property and pass that back along with the mock. 

Would it be possible to add something to either merge with an existing ISetup, or allow more meta-properties on the mock object, possibly a collection of Setups?

**Comment by stakx** [comment]
You asked this question a while ago. I'll assume that you've probably solved this problem for yourself in the meantime, so I'll close the question. If you do want to discuss this further, please just reply back and we can reopen the issue.

Here's a suggestion how you might have solved this:

Why not create a method that creates a mock for you with a particular callback:

```csharp
Mock<IFoo> CreateMockWithCallback(Action callback)
{
    var mock = new Mock<IFoo>();
    mock.Setup(foo => foo.SomeMethod()).Callback(callback).Returns(42);
    return mock;
}
```

Then inside any of your tests, call that function with a specific `Action callback` for that test:

```csharp
[Fact]
public void Test1()
{
    var mock = CreateMockWithCallback(() => DoSomething());
    …
}

[Fact]
public void Test2()
{
    var mock = CreateMockWithCallback(() => DoSomethingElse());
    …
}
```

This will probably not work if you set up a mock in the test fixture's constructor, or in some `[SetUp]` / `[TestInitialize]` method. But since you need to do some test-specific setting up anyway, and the above method would make this fairly easy (one line of code), starting to set up a mock outside of the test wouldn't actually save you much work, anyway.
