### ISSUE TITLE
MOQ Test for Hardcoded values

### ISSUE THREAD

**Issue by sameerpanicker** [moq/moq4#172]
I have a method which takes in a request object. The request object has a enum property.

Before the passed in request object is sent to the actual service, we change the enum value. i.e.

Passed enum value may be NULL or Enum Value1. Before the service call is done, the enum value is updated or hard coded i.e. 
Enum Property = Enum Value 2.

I need to write a test to check whether the passed in enum value is Enum Value 2 and nothing else.

**Comment by stakx** [comment]
Hi @sameerpanicker, to be honest, I am not certain whether you have asked your question in the right place. The issues section of this repository is targeted more at dealing with bug reports and requests for new features; that is, with the on-going development of Moq itself.

I realise that it has been a long time since you posted this, and you've probably solved the problem by now. If you still need help, I would humbly suggest that you ask on a Q & A site such as [Stack Overflow](https://stackoverflow.com). Also, it always helps if you can show a bit of code that you already have; a prose description of code is often harder to understand than the code itself. ;-)
