### ISSUE TITLE
Misleading exception when type parameter of mocked class is internal

### ISSUE THREAD

**Issue by bannmann** [moq/moq4#192]
For `new Mock<MockedClass>()`, MockedClass needs to be accessible to DynamicProxy. If it isn't, Moq produces a helpful exception message.

When mocking a generic class, say `new Mock<Container<Whatever>>`, both Container and Whatever need to be accessible to DynamicProxy. However, if the second type parameter ("Whatever") is not accessible, the exception message is very much misleading - it says

> Type to mock must be an interface or an abstract or non-sealed class.

I lost an hour isolating the real reason for this exception. Please change Moq to return an exception message similar to the first case, mentioning the correct type ("Whatever").

The following NUnit test class demonstrates the issue (provided the `InternalsVisibleTo` attribute was _not_ set on the assembly):

``` c#
class InternalClass
{ }

public class PublicClass
{ }

public class Container<T>
{
    public T Contents { get; set; }
}

[TestFixture]
public class MoqBug
{
    [Test]
    public void TestInternalClass()
    {
        var mock = new Mock<InternalClass>().Object;
        /* Exception message (good):
         * Type Your.Namespace.InternalClass is not visible to
         * DynamicProxy. Can not create proxy for types that are not
         * accessible. Make the type public, or internal and mark your
         * assembly with (...)
         */
    }

    [Test]
    public void TestInternalClassAsTypeParam()
    {
        var mock = new Mock<Container<InternalClass>>().Object;
        /* Exception message (bad):
         * Type to mock must be an interface or an abstract or non-sealed class.
         */
    }

    [Test]
    public void TestPublicClass()
    {
        var mock = new Mock<PublicClass>().Object;
        // Works fine.
    }

    [Test]
    public void TestPublicClassAsTypeParam()
    {
        var mock = new Mock<Container<PublicClass>>().Object;
        // Works fine.
    }
}
```

**Comment by stakx** [comment]
With the current version of Moq, the exception messages in your tests come directly from DynamicProxy, not from Moq.

The exception message for the `TestInternalClass` test reads:

> Message: Castle.DynamicProxy.Generators.GeneratorException : Can not create proxy for type InternalClass because it is not accessible. Make it public, or internal and […].

The exception message for the `TestInternalClassAsTypeParam` test reads:

> Castle.DynamicProxy.Generators.GeneratorException : Can not create proxy for type Container`1[[InternalClass, …]] because type InternalClass is not accessible. Make it public, or internal and […].

So what you're asking for has already been fixed in DynamicProxy.

**Comment by RipPer56** [comment]
@stakx nigga! u have a record on closing issue. you should wait for responses first.

**Comment by stakx** [comment]
@RipPer56:

> u have a record on closing issue.

Yes, I do, for the simple reason that I have been the most active collaborator here during the last year or so. During that time, I have been the only person to actually go through the issue backlog (consisting of >150 issues last May) when noone else had done that for months if not years, and I have been investing much time and effort to sort out stale and obsolete issues, and see a large percentage of the others actually resolved. Apart from the backlog, I've also dealt with around 100 issues that were newly reported. So I cannot dispute what you're saying, but also, closing issues isn't a bad thing!

> you should wait for responses first.

I find that remark of yours uncalled for and, coming from someone who hasn't invested nearly as much in Moq as the person you're addressing, even somewhat disrespectful and pretentious. If you feel that you can do a better job, why not hop on board and get to work? There are many open source projects, Moq included, that would *love* to have more active collaborators! Let us know if you're interested, e.g. over in [Moq's Gitter chat](https://gitter.im/moq/moq?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)! 🎆

And finally, I do have to wonder, what purpose would've been served by keeping the present issue open when it has demonstrably become obsolete in the meantime? Do you think it would've been better to not respond at all and let it rot by itself forever? How would that have been better than stating why it was obsolete / resolved, then closing it so that we can concentrate better on the remaining, actual issues?

I am very much open to suggestions, just please keep them constructive.

**Comment by RipPer56** [comment]
@staks

I've seen you everywhere responding to issues and i respect that. But don't be such a crybaby about a small remarque. Closing issue is a big deal because other collaborators and members filter only open issues. And in many cases, especially in roslyn repository, people are closing issues that are really helpful for the community! So for me i think closing an issue should be the responsability of its creator or in the case that he forgets about it ☺

**Comment by stakx** [comment]
@RipPer56 - well done on calling me a crybaby and a nigga. I am sure that'll help get your point across.
