### ISSUE TITLE
MockSequence

### ISSUE THREAD

**Issue by michaelhidalgo** [moq/moq4#21]
Reported by project member bcardiff, Mar 23, 2008

Implement MockSequence idea (as explained at
http://groups.google.com/group/moqdisc/browse_thread/thread/80404b259824812d
 by Eugene) on top of Moq public interface.

**Comment by regisbsb** [comment]
@kzu should we close this now?

**Comment by akazemis** [comment]
I'd like to bring this issue back to the life cuz I reckon it would be a cool feature for Moq.
Call sequence would be handy in some scenarios. Say you want to test a domain service that calls a Repository class and we want to make sure that the SaveChanges() method runs after the other methods in the repository.

**Comment by grzesiek-galezowski** [comment]
@akazemis Hi, I worked a bit on this API, but got discouraged by a long lack of reaction from the maintainer and lost my motivation. Then, there has been some new development on the main branch and there are some conflicts between my branch and the main one. I don't know what is the size of this conflict. I can help however I can if somebody wants to take over the development or I can even resume the development if I know it will not be in vain this time.

**Comment by regisbsb** [comment]
It does not fit the moq experience on second thoughts. I think if people
want something like that they can find elsewhere

**Comment by Ray-B** [comment]
@akazemis I'm on the fence with this. How badly do people need this when there are suitable work-arounds like callbacks?

@Robelind You've never needed sequence verification? This is anecdotal evidence at best. And I don't say that to offend (I'm with you on it being a smell), but I think we need a better body of evidence than that.

I've seen instances where a Cache.Clear() might be called after something like Repo.SaveChanges(). You may want to verify your SUT clears the cache after and only after. 

I will grant that a case can be made that sort of code might be indicative of a smell, but if it is, then the smell is the result a behavior on the part of the devs, and not implicity as a result of the capabilities of the mocking framework ;)

Sometimes as a developer, I just want to add some tests to some crappy legacy code someone else wrote in order to increase my confidence or understanding, and I don't have the time to do a sufficient job refactoring.

My two cents.

**Comment by firelizzard18** [comment]
Is this going to happen? Because I need to find another solution if it's not.

**Comment by stakx** [comment]
@michaelhidalgo, @grzesiek-galezowski, @Ireney, @Robelind, @regisbsb, @akazemis, @Ray-B, @firelizzard18:

I am finally closing this issue, and the pull request that goes along with it. Please see #642 for a brief explanation why I'm doing this.

I'd like to apologize in the name of the Moq team to @grzesiek-galezowski. I wasn't around 3 1/2 years ago, but back then you made a pretty big effort to drive this issue ahead, and just didn't get a response after a while. 😞 I for one appreciate your effort, call sequence verification was what originally brought me to Moq in the first place, and I'd have loved to see this enhancement fulfilled.

If anyone would like to pick up work on this issue, please post here and we'll see what we can do.
