### ISSUE TITLE
Mock any instance

### ISSUE THREAD

**Issue by ggsilva** [moq/moq4#214]
Hi. You could implement the feature of mock any instance of a class? So I do not need dependency injection.

Example:

Mock.SetupAny<MyClass>(anyInstance => anyInstance.DoSomething()).Returns(something);

**Comment by kzu** [comment]
Sounds like AutoFixture?

**Comment by ggsilva** [comment]
Sorry about my English.

It would be something more like the java has:

http://docs.mockito.googlecode.com/hg/org/mockito/Matchers.html#any ()

**Comment by ploeh** [comment]
AutoFixture isn't a dynamic mock library (but it *does* [integrate with Moq as an option](http://blog.ploeh.dk/2010/08/19/AutoFixtureasanauto-mockingcontainer)), so the above doesn't sound like AutoFixture.

It's not clear to me what this issue is suggesting, but Moq does work with concrete classes as well as abstract classes and interfaces. Moq can do [anything you, as a programmer, can do](http://stackoverflow.com/a/1973482/126014), but nothing more.

Could the apparently more powerful capabilities in Java be due to the fact that in Java, all class members are virtual (and thus, overridable) by default, whereas with typical .NET languages, you have to explicitly make members virtual - which means that most aren't?

**Comment by stakx** [comment]
@ggsilva, this issue has been inactive for some time, so I am closing it for the time being. If you are still interested in discussing this, just reply back and we can reopen it.

(That being said: Moq is not a DI container, and it probably doesn't want to become one. Therefore it seems unlikely to me that features would be added so that it could be used as one. If DI is what you need, you're better off using the right tool for that; e.g. Autofac, Ninject, or Unity.)
