### ISSUE TITLE
The Microsoft Connect link give me *page not found*

### ISSUE THREAD

**Issue by davidshen84** [moq/moq4#219]
The [Microsoft Connect](https://connect.microsoft.com/VisualStudio/feedback/ViewFeedback.aspx?FeedbackID=318122) link on the [Quickstart](https://github.com/Moq/moq4/wiki/Quickstart) page gives me **page not found** message. Maybe it should be updated?

**Comment by stakx** [comment]
I assume that these days, one would ask for C# / VB.NET language features over at https://github.com/dotnet/roslyn/issues. Unfortunately, they currently have over 3,000 open issues, if anyone can track down the issue corresponding to the old issue on Microsoft Connect, a pointer to it would be much appreciated.

(As far as I can tell, the Microsoft Connect issue must have been about allowing conversion operators from a user-defined type to an interface type. For Moq, this would be valuable because it would allow an implicit conversion from `Mock<T>` to `T`, thereby making `Mock.Object` redundant.
