### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by Tohnmeister** [moq/moq4#247]
Not really an issue with Moq functionality, but more with this repository. In my company we're using the latest stable release of Moq. One of the things we're doing to guarantee contingency, is to have source code of third party binaries also in our versioning system. With that in mind I was looking for the source code belonging to the latest stable release of Moq (4.2.1510.2205). But the releases tab on this project's Github page only shows one old release and tag.

Is there a way to get the source code of a specific release?

**Comment by stakx** [comment]
See also #320.

Releases are not currently tagged, but if you know that a new NuGet package is published whenever a commit is made to `master`, and when that commit passes all checks on the build server, then you should be able to locate the commit corresponding to a particular NuGet package fairly easily.

I agree that release tags would help. Until (if) they get added to the repository, here's a small how-to on how to locate the commit corresponding to a particular NuGet package version. (Disclaimer: This is to the best of my knowledge, but since I am still piecing things together for myself, I could be wrong.)

Let's assume that you are interested in the source code for Moq version 4.7.11.

1. According to the version history [on NuGet](https://www.nuget.org/packages/Moq), version 4.7.11 was published on 30 May 2017:

    ![moq-nuget-version-history](https://cloud.githubusercontent.com/assets/104481/26756634/6837747c-48a7-11e7-807f-fa869fe28945.png)

    Note that this is not the only package released on that date. But it was the first of the two packages to be released on that day.

2. Back on GitHub, take a look at the [commits on the `master` branch](https://github.com/moq/moq4/commits/master) and go to the date you identified in the previous step:

    ![github-commit-history](https://cloud.githubusercontent.com/assets/104481/26756655/df8a054e-48a7-11e7-93b3-59c6a8fcdd09.png)

    As you can see, only two out of four commits on that day passed the CI server checks, which is why there are two packages on NuGet. Above we noted that the one you're interested in is the one that was published first, so it corresponds to the commit `538ded1`.

Hope this helps for the moment.

**Comment by stakx** [comment]
I've now added release tags for all published NuGet packages all the way back to version 4.5.0.

I haven't yet figured out how versioning was done in the 4.2.x versions, but once I do, I'll add those release tags as well.

**Comment by stakx** [comment]
I figured out a way to add the missing release tags for versions <4.5.0. Using tools such as JustAssembly, ILSpy, `git log -S` (pickaxe) and gitk I can identify differences between versions and track down the commits responsible for them. It's quite a bit of work, but I'm close to getting this done completely.

Tags will be greatly helpful in creating more precise release notes (see #320) and those in turn will aid in tracking down regressions.

**Comment by stakx** [comment]
@Tohnmeister: All release tags for Moq v4 are now added to the repository.

**Comment by Tohnmeister** [comment]
Awesome! Exactly what we needed. Thanks.
