### ISSUE TITLE
SetUpAllProperties does not provide stubbing behavior for virtual properties.

### ISSUE THREAD

**Issue by apeneve** [moq/moq4#283]
I have a simple `public virtual string Foo {get;set;}` on my class to be mocked.
The mocked object does not remember the value I pass in via `mock.Object.Foo = "bar";` even after i call `mock.SetUpAllProperties()`.

As far as I can tell this used to work in an older version. Isn't "stubbing" or "property behavior" supposed to work with virtual properties?

**Comment by stakx** [comment]
Do you mean something like the following?

```csharp
[Fact]
public static void MockRemembersPropertyValue()
{
    var mock = new Mock<C>();
    mock.SetupAllProperties();
    mock.Object.Foo = "bar";
    Assert.Equal("bar", mock.Object.Foo);
}

public class C
{
    public virtual string Foo { get; set; }
}
```

This test passes in the current version of Moq, so this might have been fixed in the meantime.

If I misunderstood your scenario, please report back with a small but complete repro code and an indication of which version of Moq you're using. In the meantime, I am closing this issue as "non-reproducible error".
