### ISSUE TITLE
Who's using Moq?

### ISSUE THREAD

**Issue by fabiogouw** [moq/moq4#372]
Hello. I'm preparing a presentation to advocate the use of Moq at the place I work. To make this presentation more robust, I'd like to list famous projects that uses this library. Does anyone here help me with this?

Thanks

**Comment by stakx** [comment]
I personally cannot provide any substantial help, sorry. I simply wouldn't know where to begin.

I guess you could look at who starred / forked the repository, who submitted issues / pull requests, or who blogged about it, and follow up on those, but that will give you a incomplete picture at best. If you want Big Name Companies&trade; mentioned in your presentation, if such a company has any open-source projects, you might want to check them out, too.

Or try selling Moq primarily for its own merits, and not just because who else uses it. :-)

**Comment by fabiogouw** [comment]
Thanks for your answer, @stakx 

I'm selling Moq to people that had preference for Moles because it had "Microsoft's support", so for them it's important to have references. But at least I was able to find some interesting statistics at Nuget's website:

- Moq is the only testing library listed on the top 100 downloaded packages
- 5500 is the average downloads per day

I hope these numbers can help me!

**Comment by stakx** [comment]
You'll find out. ;)

Btw. one argument against Moles (but please verify this yourself!) is that in order to offer the amazing functionality that it does (it can even mock static classes!), it has to rely on one of the CLR's unmanaged APIs (IIRC the unmanaged profiler API), which is COM-based, which is specific to the Windows platform. Meaning that Moles/Fakes is unlikely to work under .NET Core. This may or may not be important to your company, of course.

**Comment by michal-ciechan** [comment]
Just my 2 cents, I have worked at numerous financial institutions over last decade or so, and other than using Rhino.Mocks (when Moq wasn't around and/or discovered by me/team I was on) Moq has been used extensively. Haven't come across anyone using anything else in the last 4/5 years within around 15-20 teams!

**Comment by natemcmaster** [comment]
FWIW - [my team](https://github.com/search?q=org%3Aaspnet+moq&type=Code) loves Moq.

**Comment by fabiogouw** [comment]
@michal-ciechan , I agree with you, the places I've worked all used Moq too. But today my challenge is to persuade people who's not used to unit testing.

@natemcmaster , I gotta say your team rocks! Having ASP.NET / Microsoft's projects using Moq is great to convince my coworkers.

**Comment by stakx** [comment]
@fabiogouw: How did your presentation go? :-)

**Comment by fabiogouw** [comment]
@stakx , unfortunately my meeting has been postponed  :disappointed: 

As soon as I get news, I'll share them with you guys.

Thanks

**Comment by stakx** [comment]
@fabiogouw, I'm closing this issue for now, since you've probably prepared your presentation and have gathered the information you needed for it. Please feel free to post your success story (hopefully!) here anyway. :-)

**Comment by fabiogouw** [comment]
Sure, @stakx , thank you!

**Comment by kzu** [comment]
Roslyn and ASP.NET should be enough references, I'd say ;)

**Comment by fabiogouw** [comment]
Everything went well in my presentation! I appreciate the contributions given, they were very valuable.
