### ISSUE TITLE
CallBase=true does not work if mock is created with Mock.Of<T>() instead of new Mock<T>()

### ISSUE THREAD

**Issue by Damian-Pumar** [moq/moq4#419]
```csharp
this.entity = Mock.Of<Entity>();

Mock.Get(this.entity).CallBase = true;

// code...
```

virtual method not call base method.

Thanks

**Comment by stakx** [comment]
Could you please post a short but complete repro code that demonstrates the problem you're having? Please also state explicitly what goes wrong (i.e. what you expect to happen, and what happens instead). Thanks!

**Comment by Damian-Pumar** [comment]
Attach example
[Example.zip](https://github.com/moq/moq4/files/1145604/Example.zip)

Thanks

**Comment by stakx** [comment]
Sorry but that code does not compile. Where is the full class definition? Where is the base class? What is `this.contrato`? All of that being said, your code does not contain a single `virtual` method.

**Comment by Damian-Pumar** [comment]
Sorry, I rewrite original code into example.
[Example.zip](https://github.com/moq/moq4/files/1145812/Example.zip)

Thanks

**Comment by stakx** [comment]
OK, after a few minutes of fiddling with your code to get it to work I think I see what you mean. Let me try to summarise your code:

```csharp
[Fact]
public static void CallBase_should_also_take_effect_when_mock_is_created_using_Mock_Of()
{
    var entity1 = new Mock<Entity>() { CallBase = true }.Object;
    Assert.True(new MyTarget(entity1).IsValid);  // passes

    var entity2 = Mock.Of<Entity>();
    Mock.Get(entity1).CallBase = true;
    Assert.True(new MyTarget(entity2).IsValid);  // fails
}

public class MyTarget
{
    private Entity entity;

    public MyTarget(Entity entity)
    {
        this.entity = entity;
    }

    bool IsValid => this.entity.VirtualProperty;
}

public class Entity
{
    public virtual bool VirtualProperty => true;
}
```

I suspect the difference in behavior here is due to `Mock.Of<T>()` setting up all properties while `new Mock<T>().Object` doesn't set up anything, but that's just a first guess; some more digging is required.

**Comment by Damian-Pumar** [comment]
Ok, Perfect!
I will replace Mock.Of<T>();  for new Mock<T>();

Thank you!
Regards.

**Comment by stakx** [comment]
I've been looking into this again, and yes, the difference is caused by the fact that unlike `new Mock<T>()`, `Mock.Of<T>()` also performs a `SetupAllProperties()`, which creates a setup for all properties. `Mock.CallBase` only takes effect with properties and methods for which there is no matching setup; if there *is* a setup, the base implementation only gets involved iff `.CallBase()` was specified for that particular setup.

IMHO it is rather confusing that `Mock.Of<T>()` has such different semantics than `new Mock<T>()`, but it's probably too late to change that without breaking lots of existent code out there.
