### ISSUE TITLE
Issue with Moq.pdb in version 4.7.99: "Symbol indexes could not be retrieved"

### ISSUE THREAD

**Issue by epot** [moq/moq4#428]
I am getting an error when trying to publish the symbols:
    
    Symbol indexes could not be retrieved.

**Comment by stakx** [comment]
Can you please describe in more detail what you're attempting to do? (For example, as I understand it, you should consume the symbols, not publish them. What location are you publishing to?)

**Comment by epot** [comment]
Thanks for the quick answer! To be honest, I am not sure what is going on under the hood. I am using a TFS build that has a step "Index sources & publish symbols". That step was working with my previous moq dependency (4.7.1) and not anymore. I will try to find out more about what it is trying to do.

**Comment by stakx** [comment]
I'm wondering why TFS would even attempt to source-index a third-party dependency's PDBs.

The change here (as mentioned in the [changelog](https://github.com/moq/moq4/blob/master/CHANGELOG.md#4799-2017-07-17)) is that Moq 4.7.99 now includes PDBs again (for the first time since version 4.5.7), and they are **already** source-indexed.

I suppose you might want to simply exclude that PDB from the build step you mention, if that is an option?

**Comment by epot** [comment]
I will check that, I wonder indeed why it does not only work on my component pdb.

**Comment by stakx** [comment]
@epot: Possibly because your component uses the classic PDB format (`full`, `pdb-only`)? Moq uses the relatively new `portable` PDB format. The people at Microsoft clearly say that there are still many tools that don't understand this new format, but it's the future and that's where they invest their efforts.

**Comment by Magrangs** [comment]
I am also getting the same issue with a hosted buid in team services online

**Comment by stakx** [comment]
As suggested in [this comment over at sendgrid/sendgrid-csharp#494](https://github.com/sendgrid/sendgrid-csharp/issues/494#issuecomment-317065010) I might also change the .NET 4.5 target's PDB back to `<DebugType>full</DebugType>` so you can upgrade again (if you want :-). I've subscribed to that other issue and will wait to see how it resolves.

**Comment by gregveres** [comment]
+1 I hit this tonight. I backed off to the previous version and the build is working just fine for now. I will keep an eye out for a new version that works with VSTS and .Net 4.5.

Thanks

**Comment by stakx** [comment]
Unfortunately we cannot resolve this issue like the Sendgrid folks did, because we're source linking the Moq PDBs, and SourceLink isn't supported yet for classic / Windows PDBs. This will change with Roslyn / VS 15.3, see  https://github.com/dotnet/roslyn/pull/18539.

We have three options on how to proceed:

1. Remove the PDBs for the .NET 4.5 target until Microsoft's own tooling has better support for portable PDBs. Who knows how much longer that is going to take.

2. Revert from SourceLink to GitLink for the .NET 4.5 target. That would be unpleasant because Moq's GitLink setup was never verified as working, so this would possibly be much work for only a temporary gain.

3. Wait until Roslyn 15.3 is out, then switch to a full Windows PDB (instead of portable PDB) for the .NET 4.5 target, recompile with Roslyn 15.3 and republish.

My personal preference is option (3).

**Comment by rh072005** [comment]
We've just run in to this same issue. Now that 15.3 has been released is this back on the radar to move over Windows PDBs?

**Comment by stakx** [comment]
@rh072005 - only just updated to VS 2017.3. I'll look into it over the next few days. This should be doable if @ctaggart's SourceLink tools work for Windows PDBs.

**Comment by stakx** [comment]
@epot, @Magrangs, @gregveres, @rh072005 - I have prepared a potential fix for your issue (switching from portable PDBs back to classic PDBs, see [these commits in my fork's `sourcelink-nonportable-pdbs` branch](https://github.com/moq/moq4/compare/master...stakx:sourcelink-nonportable-pdbs)), but I can't actually test it as I don't have access to TFS. Would any of you be willing to test an out-of-band prerelease version of Moq (4.7.100-pre, temporarily available [here](https://www.myget.org/feed/stakx-testing/package/nuget/Moq)) and see if the problem disappears?

**Comment by stakx** [comment]
@epot, @Magrangs, @gregveres, @rh072005 - I have prepared a potential fix for your issues (switching from portable PDBs back to classic PDBs, see the PR referenced above), but I can't actually test it as I don't have access to TFS. Would any of you be willing to test an out-of-band, prerelease version of Moq (4.7.100-pre, temporarily available [here](https://www.myget.org/feed/stakx-testing/package/nuget/Moq)) and see if it resolves your issues?

**Comment by rh072005** [comment]
@stakx I've just given that a go and it's working for us

**Comment by stakx** [comment]
OK this should be fixed by #443 in the next release of Moq (version > 4.7.99).

It would be a pity if Moq had to remain with classic PDBs forever, I guess we'll make the switch back to portable PDBs sometime in the future (perhaps in 2018). Until then let's give the new portable PDB format some more time to gain momentum and better tooling support.

**Comment by TechWatching** [comment]
I had the same issue, thanks for correcting it :) When is next released planned ?

**Comment by stakx** [comment]
@TechWatching: I am still waiting for feedback on one or two issues, but I was looking at publishing an updated version of Moq in the next 2 weeks or so.

**Comment by stakx** [comment]
Just for those of you still watching this issue, version 4.7.127 is out. Back to Windows PDBs, hope this helps.
