### ISSUE TITLE
Getting errors when attempting to setup a method with an out parameter

### ISSUE THREAD

**Issue by sspringer** [moq/moq4#436]
I am having a very difficult time attempting to mock the ASP.Net Core IMemoryCache object.  I have the mock set up as follows:

    var memoryCacheMoq = new Mock<IMemoryCache>();
    Lookup dummy = new Lookup {  };
    memoryCacheMoq.Setup(m => m.TryGetValue(It.IsAny<object>(), out dummy)).Returns(false);

I want the method to return false so my database mock performs what it's supposed to do.

When I debug this, I get the following error when it gets to the setup line:

>Message: System.NotSupportedException : Invalid setup on an extension method: `m => m.TryGetValue<Lookup>(It.IsAny<Object>(), .dummy)`

From everything I've read, and even watched an  example on PluralSight, this is the way to set this up.

Any assistance is greatly appreciated!  Thank you.

**Comment by stakx** [comment]
Note that there are two methods on `IMemoryCache` called `TryGetValue`, one of them being an extension method:

1. `bool TryGetValue(object key, out object value)` defined in `IMemoryCache` 
2. `bool TryGetValue<TItem>(this object key, out TItem value)` defined in `Microsoft.Extensions.Caching.Memory.CacheExtensions`

You're trying to set up the latter overload, since `dummy` is not typed as `object`. Extension methods are static methods and cannot be intercepted / dealt with by Moq, therefore the error message.

Here's something for you to try: Declare `dummy` as `object` so that you're setting up the non-generic interface method instead of the generic extension method. I'd wager that the extension method is using the interface method internally and simply decorating it with a type cast from `object` to `TItem`, so setting up the interface method might give you the desired effect. Also, chances are that you're not actually going to use the value stored in `dummy` anyway, so you're not loosing much by giving up some type accuracy.

```csharp
object dummy;
memoryCacheMock.Setup(m => m.TryGetValue(It.IsAny<object>(), dummy)).Returns(false);
```

Does that resolve your problem?

**Comment by sspringer** [comment]
That did the trick!  Now I have to figure out how to circumvent the "Set" extension method.  Grrr.

Anyway, that did solve my immediate issue.  Thanks!

**Comment by tiagocrizanto** [comment]
@sspringer Well I reach this page and find an anwser. So it this solution could be useful for other Moq users. I find this way to mock the **Set** of IMemoryCache with Moq

```cs
memoryCacheMock
    .Setup(x => x.CreateEntry(It.IsAny<object>()))
    .Returns(Mock.Of<ICacheEntry>);
```
