### ISSUE TITLE
I just upgraded to Castle Core v4.2.0 whilst using Moq v4.7.127 and I am getting an assembly binding error

### ISSUE THREAD

**Issue by fir3pho3nixx** [moq/moq4#461]
I just upgraded Castle.Core from v4.1.1 to v4.2.0 whilst using Moq and got an assembly binding error. Why is this happening?

**Comment by fir3pho3nixx** [comment]
This is because Castle Core changed the AssemblyVersion attribute to only include major version numbers only so that we can avoid assembly binding errors with future releases/upgrades of Castle Core.  

### Why is the assembly binding error happening then?

This is because Moq have to release a version compiled against the new AssemblyVersion strategy, they are on it! :)

### What do I do in the meantime? I want Castle Core bug fixes.

You can apply this following assembly binding redirect in your App.config.

```
 <dependentAssembly>
    <assemblyIdentity name="Castle.Core" publicKeyToken="407dd0808d44fbdc" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="4.0.0.0" />
  </dependentAssembly>
```

### Are you using Castle Core features directly?

If not and you are using the latest version of Visual Studio (15.3.5) then you should probably remove the NuGet reference altogether along with it's assembly bindings. This means Castle Core becomes a `transitive dependency` which you should not have to worry about. 

### Are you guys versioning properly at all?

Yes we are, we just use the AssemblyFileVersion instead. 

![image](https://user-images.githubusercontent.com/607402/31030491-6f672352-a54d-11e7-95d4-5d10b2ad3158.png)

### I am still having issues. 

Please post to this issue and we will try to help you.

**Comment by fir3pho3nixx** [comment]
https://github.com/castleproject/Core/issues/307

**Comment by stakx** [comment]
FYI, everything is ready to publish an updated Moq version that it built against Castle Core 4.2.0, unfortunately our CI server (AppVeyor) currently cannot push the built package to NuGet. Will report back here when that problem is resolved and when the new package is available.

**Comment by baynezy** [comment]
@stakx - you know there is a workaround [outlined on there support forum](http://help.appveyor.com/discussions/problems/8215-cannot-publish-to-nuget-get-400-bad-request-error). So that you can publish while they fix it.

**Comment by stakx** [comment]
@baynezy - Thanks for the link. Yes, I've been watching that support thread since Saturday. However, I am not very eager to apply the workaround because frankly, in my opinion, it is *their* problem to fix. (Actually, it's ultimately the NuGet team that should straighten things out, but well.)

I realise that this kind of attitude doesn't get us anywhere with the present issue, and I apologize for not being more helpful right now. If the CI problem won't be solved by the end of the week, I will think about applying the workaround.

Another reason why I'm willing to wait (apart from insisting on principles) is that we might just skip version 4.7.137 altogether and go straight to version 4.8 around the weekend. Changing the AppVeyor configuration file now will cause a minor mess with our changelog and Git history (due to our use of GitInfo), while including that change with 4.8 wouldn't, so I'd be preventing avoidable cleanup work.

I'd advise everyone to downgrade to Castle Core 4.1.1 until the next Moq version is out. Afterwards, you'll be able to update all you want. :-)

**Comment by stakx** [comment]
**Moq 4.7.137 has just been published on NuGet.** It references Castle Core 4.2.0, so once you upgrade, any version conflicts should resolve itself.

If anyone still has trouble, please let us know here.

**Comment by stakx** [comment]
(I realise it's a little soon to close this notification, but given that the most likely way to cause this problem is to just press something like a "update everything to the latest version" button, this should really be solved now. Thanks again for posting this!)

**Comment by fir3pho3nixx** [comment]
No problem! :)

**Comment by salixzs** [comment]
Starting 4.8 Moq just doesn't work on any of build servers with this
```
Initialization method {Here is a test class] threw exception. System.TypeInitializationException: The type initializer for 'Moq.Mock`1' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Moq.ProxyFactory' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Moq.CastleProxyFactory' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Castle.Core, Version=4.2.1.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).
```
I understand that reasons are somewhere there - NuGets, Versions, BindingRedirects, Microsoft way of versioning etc. etc. ... but the fact is - this happens each time I touch Moq. 
Currently adding Moq (4.12) to project (we still need full 4.7.2 Framework here) it also adds Castle.Core, System.Runtime.CompilerServices.Unsafe and System.Threading.Tasks.Extensions NuGet packages. I am just tired with this. Changing to alternative mocking library was faster than trying to find and make Moq work again.
Sorry, Moq is great library, but it is just not working anymore.

**Comment by stakx** [comment]
@salixzs: You appear to be using an older version of Moq. Why not try with the latest one? We've since shed quite a few package dependencies, and both Moq and Castle.Core have migrated to a different assembly versioning approach which should greatly help in avoiding assembly binding errors.

Yes, I'm tired of this, too. I've found however that using the latest tooling and using SDK-style project file format helps a lot.
