### ISSUE TITLE
Allow the equivalent of It.IsAny with ref parameters in `Setup`

### ISSUE THREAD

**Issue by ohadschn** [moq/moq4#479]
Following https://github.com/moq/moq4/issues/105, it would be nice to be able to match any value of a passed by ref variable in `Setup`.

Per https://github.com/dotnet/csharplang/issues/158 that can't currently be achieved using `ref returns` (e.g. `ref T It.IsAnyRef<T>`) with the current overloads that take expression trees.

However, it might be doable by accepting a delegate and decompiling it into an expression tree at runtime. That would involve quite some work though, and for something this specific perhaps the following would suffice:

```cs
mock.Setup(m => m.MethodWithByRefParams(...))
    .DoNotMatchByRefParams()
    ...;
```

**Comment by stakx** [comment]
Like you said, the C# language currently doesn't allow us to do this nicely, and lambda decompilation is possible (see e. g. [this proof-of-concept prototype](https://github.com/stakx/DelegateDecompiler) I cooked up a while ago), but will require Moq to become dependent on .NET Standard 2, and it would take some more work&mdash;I'd like to keep this open as an option for a 4.9 release or later.

For now, the least we *can* do is to add a helper method that "disables" matching for `ref` parameters, like the `.DoNotMatchByRefParams()` you suggested. I'll look into this.

**Comment by stakx** [comment]
@ohadschn - A quick question: Do you think a feature switch (`Mock.Switches |= Switch.DoNotMatchRefParameters`) instead of a setup verb `.DoNotMatchRefParams()` would also be agreeable?

The reason behind this is that I've realised that a `.DoNotMatchByRefParams()` setup method would only work in combination with `mock.Verify()` or `mock.VerifyAll()`, but not when you do a `mock.Verify(m => m.Method(...))`.

A feature switch, on the other hand, however could apply to *all* `Verify` calls:

```csharp
var mock = new Mock<IHaveMethodsWithRefParameters>();
mock.Switches |= Switch.DoNotMatchRefArguments;
...
mock.Verify(m => m.Method(1, ref dummy, 2), ...);
```

**Comment by ohadschn** [comment]
How about something like

`mock.NoRefArgMatching().Verify(...)`

Where NoRefArgMatching() is a wrapper with the switch enabled?
That way you can still decide to match refs on a case by case basis.

**Comment by stakx** [comment]
That would be a nice solution. Unfortunately it wouldn't be thread-safe. 🙁

**Comment by ohadschn** [comment]
I agree about managing this state, I was actually thinking about creating a new Mock with the same underlying object..  would that be possible?

**Comment by stakx** [comment]
In theory, possibly yes. One would create a new `Mock<T>` object sharing all internal state with the original except for the switch state. In practice, this would take *a lot* of work to ensure this doesn't cause more trouble than it solves. I'd estimate that this approach isn't worth the effort.

**Comment by ohadschn** [comment]
How about something like
```cs
mock.Verify(m => NoRefVerify(m.Method(1, ref dummy, 2)), ...);
```

Where `NoRefVerify` simply returns whatever it gets and is only there for your expression analyzer to be able to catch?

**Comment by stakx** [comment]
Out of curiosity, can I take your efforts to find an alternative syntax as a sign that you don't find the feature switch acceptable?

Your last suggestion just gave me an idea. Why not this:

```csharp
mock.Setup(m => m.Method(…, ref It.Ref<int>.IsAny, …));
//                          ^^^^^^^^^^^^^^^^^^^^^
```

Obviously the generic parameter is in the wrong place (it would ideally follow `IsAny` instead of preceding it), but I believe this would actually be feasible if `It.Ref<int>.IsAny` were a dummy static field declared as follows:

```csharp
static partial class It
{
    public static class Ref<T>
    {
        public static T IsAny;
    }
}
```

(Credits go to @michal-ciechan, the above technique is inspired by what he did in #343.)

**Comment by ohadschn** [comment]
Nice! Maybe `It.IsAny<int>.Ref`?

**Comment by stakx** [comment]
There's already `It.IsAny<T>()`, it's unfortunately not possible to overload the method with a type.

**Comment by ohadschn** [comment]
Well I suppose you could do `ItIs.Any<int>.Ref` :)
But really the name isn't that important, whatever works would be great.

**Comment by stakx** [comment]
All done. As a small bonus, "any" matching for `ref` parameters is now also directly supported with `.Protected()` setups:

```csharp
mock.Protected().Setup("ProtectedMethod", …, ItExpr.Ref<int>.IsAny, …);
```

**Comment by stakx** [comment]
@ohadschn - I just published a [pre-release version 4.8.0-rc1 on NuGet](https://www.nuget.org/packages/Moq/4.8.0-rc1). It has all the new `ref` stuff (among other things) that we've been discussing in several issues. Feel free to test away.

**Comment by asyle83** [comment]
Hi, I have a problem with a method that has a ref parameter of type Array:
`Method(int param1, string param2, ref Array param3)`
param3 is an output parameter and must be not null in order to continue the code execution but I don't know how to mock it.
I tried:
`_mock.Setup(m => m.Method(It.IsAny<int>(), It.IsAny<string>(), ref It.Ref<Array>.IsAny));`
and also
`_mock.Setup(m => m.Method(It.IsAny<int>(), It.IsAny<string>(), ref arrayTest));`
where arrayTest is an array populated with some data.

But in any case during the test execution, the ref parameter is always null...
How can I solve?
Thanks

**Comment by stakx** [comment]
Sorry, accidentally pressed button.
