### ISSUE TITLE
System.MissingMethodException in Moq

### ISSUE THREAD

**Issue by stevejbrother** [moq/moq4#555]
I opened up a question on [StackOverflow ](https://stackoverflow.com/questions/47831031/using-moq-testing-overloaded-methods-get-system-missingmethodexception-method) where I'm getting the MissingMethodException. I'm using MSTest build where I have an overload method to Create or Update some items in an MySQL Database where I need to include transactions. Given that MySQL does not do nested transactions, I had to do an overload of methods. Problem is, even before I do a unit test and trying to set up the Moq, I get MissingMethodException thrown; yet, when I run it using MySQL database to test it out, it works fine.

This is what I have:
`Mock<IProductsRepository> _ProductRepositoryMoq = new Mock<IProductsRepository>();

            _ProductRepositoryMoq.Setup(r => r.CreateNewProductItem(It.IsAny<ProductExt>()))
                .ReturnsAsync((ProductExt p) =>
                {
                    p.ID = productList.Last().ID + 1;
                    return p.ID;
                });
            _ProductRepositoryMoq.Setup(r => r.CreateNewProductItem(It.IsAny<ProductExt>(), It.IsAny<MySqlConnection>(), It.IsAny<MySqlTransaction>()))
                .ReturnsAsync((ProductExt p, MySqlConnection c, MySqlTransaction t) =>
                {
                    p.ID = productList.Last().ID + 1;
                    return p.ID;
                });`

Now the first method with just a ProductExt parameter works fine in the Moq, but it's the second overloaded method that's giving me the MissingMethodException but as I stated, it is indeed working and I have verified through the database that data is being inserted and/or modified.

Something is telling me that there's a problem with Moq or I'm not setting this up correctly. How is it that it's working with the database, but not with a Moq?

Did I really find a bug, or am I doing a newbie mistake, and if so, where did I go wrong and how do I set it up correctly?

**Comment by stakx** [comment]
I saw your question on Stack Overflow, and I commented there that the error you're seeing isn't reproducible with just the code shown.

There's no reason to assume that the problem lies with Moq before you have ruled out some DLL versioning problem. What version of Moq does your project reference? What verdion of `Moq.dll` do you actually have in your binaries folder? Are there any other NuGet packages depening on Moq, and if so, what versions do they reference? Do you have any assembly binding redirects set up in `App.config` or `Web.config`? Have you tried deleting your solutions' binaries folders, clearing your NuGet package cache, then performing a package restore and rebuild?

If you've done all that and you're still seeing the provlem, please post a small, standalone project that exhibits the problem. Otherwise there's not much we can help you with.

**Comment by stakx** [comment]
Turns out this is possibly a duplicate of #566.
