### ISSUE TITLE
Add documentation to NuGet package and/or have updated easy to find online documentation

### ISSUE THREAD

**Issue by LJNielsenDk** [moq/moq4#57]
Add documentation to NuGet package and/or have updated easy to find online documentation.

**Comment by stakx** [comment]
Hi @LJNielsenDk, it has been a long time since you posted here. Are you still interested in this issue? If so, please report back sometime during the next two weeks or so; otherwise I'll close this issue. Some quick feedback and questions:

> Add documentation to NuGet package

What exactly did you have in mind?

The NuGet package includes the API documentation in the form of XML documentation comments. These are accessible via Visual Studio's IntelliSense and/or the Object Browser tool window.

It would be somewhat unconventional to include, say, a PDF or CHM file in the NuGet package. Full documentation is usually found online these days. 

> have updated easy to find online documentation

Regarding "easy to find", the readme page points to the [Quickstart](https://github.com/Moq/moq4/wiki/Quickstart) guide as well as the [API reference documentation on NuDoq](http://www.nudoq.org/#!/Projects/Moq), as well as to some blog posts. Is that sufficient? Or do you have suggestions how the status quo could be improved?

Regarding "up-to-date", the documentation on NuDoq is indeed out of date. This is being tracked in #354.

**Comment by stakx** [comment]
I'm closing this issue for now, since it's not exactly clear what is being asked for. I'm happy to reopen this issue if you have further comments or suggestions!
