### ISSUE TITLE
Mock.Of() and MockRepository.VerifyAll()

### ISSUE THREAD

**Issue by robrich** [moq/moq4#617]
**Problem:** Mocks created with `Mock.Of()` aren't in `MockRepository`.

```
var repo = new MockRepository(MockBehavior.Strict);
var mock = Mock.Get(Mock.Of<IService1>());
mock.Setup(m => m.Do());
repo.VerifyAll(); // <-- no exception thrown
mock.VerifyAll(); // <-- exception thrown here
```

**Propose:**

`MockRepository.Add(Mock<T> mock)` used like so:

```
var repo = new MockRepository(MockBehavior.Strict);
var mock = Mock.Get(Mock.Of<IService1>());
mock.Setup(m => m.Do());
repo.Add(mock);
repo.VerifyAll(); // <-- exception thrown here
```

**Comment by robrich** [comment]
I am familiar with `repo.Create<T>()`, but I'm having trouble weening people off the elegance of `Mock.Of()`.  As noted in https://github.com/tkellogg/Moq.AutoMocker/issues/33 I'm looking for a way to add mocks to the repository's `.VerifyAll()` list that aren't created through `repo.Create<T>()`.  Alternatively, I can keep my own list, but then I need a way to throw a single `MockException` for everything in the list, but there's no public constructor for `MockException`.  https://github.com/moq/moq4/blob/master/Source/Obsolete/MockFactory.cs#L375 keeps everything so private.

**Comment by stakx** [comment]
@robrich: `MockException` isn't meant to be instantiable from outside Moq. Also, it doesn't really make much sense to give a repository the ability to add any (externally created) mock to it. IMHO the cleanest option would be to add something corresponding to `Mock.Of<T>` to `MockRepository` proper.

Since the public API of Moq 4 is currently frozen due to Moq 5 being made ready for initial publication, we can't push such an API enhancement forward right now (even though it would be a trivial addition).

I shouldn't even suggest the following, as it intentionally breaks an abstraction... but you *could* do this:

```csharp
sealed class MockOfRepository : MockRepository
{
    public MockOfRepository(MockBehavior defaultBehavior) : base(defaultBehavior) { }

    public T Of<T>(Expression<Func<T, bool>> predicate) where T : class
    {
        var mockObject = Mock.Of<T>(predicate);
        var mock = Mock.Get(mockObject);
        var mocks = this.Mocks as ICollection<Mock>;
        mocks?.Add(mock);
        return mockObject;
    }
}
```

Obviously, the `this.Mocks as ICollection<Mock>` isn't exactly clean code (`this.Mocks`'s declared static type is `IEnumerable<Mock>`), and might break in a future version of Moq.

**Comment by robrich** [comment]
Would you accept a PR to put `mockRepository.Of<T>()` into the v5 branch?

Agreed, this solution is perfect except for the obvious fragility of assuming unsafe internals that are already flagged to change.

**Comment by stakx** [comment]
/cc @kzu:

> Would you accept a PR to put `mockRepository.Of<T>()` into the v5 branch?

**Comment by stakx** [comment]
@robrich - It appears that I've been away too long from Moq's code base, or from this issue... but I'm not exactly sure anymore why we've even been discussing this. Aren't the following existing methods what you're looking for?:

https://github.com/moq/moq4/blob/d4aea9c344330b35487a2780736b04167e5ecb4a/Source/Linq/MockRepository.cs#L18-L38

The only catch here is that these existing methods return an `IQueryable<T>` so you'll have to call `.First()` on it. For example:

```csharp
MockRepository mocks = ...;
var foo = mocks.Of<IFoo>(f => ...).First();
```

**Comment by stakx** [comment]
@robrich - Can we close this issue, or is the above solution `MockRepository.Of<T>(...).First()` not an option for you?

**Comment by robrich** [comment]
Yes, we can close this.  All else being equal, I still see value in making the `.VerifyAll()` process more SOLID, but that's definitely jumping the shark here.
