### ISSUE TITLE
Mocking extension methods used on a mocked object

### ISSUE THREAD

**Issue by FireEmerald** [moq/moq4#620]
Mocking an extension method itself isn't possible but it is (/should be) in fact possible to mock a call of an extension method on a mocked object.

As an example i use RhinoMocks which is quite identically with Moq:
```c#
[Test]
public void MoqFails()
{
	var qCar = new Mock<ICar>();
	qCar.Setup(x => x.GetDriverName()).Returns("Doe"); // Fails

	// > System.NotSupportedException: Invalid setup on an extension method:
	// > x => x.GetDriverName()
}

[Test]
public void RhinoMocksWorks()
{
	var rCar = MockRepository.GenerateMock<ICar>();
	rCar.Expect(x => x.GetDriverName()).Return("Doe"); // Works
	Assert.That(rCar.GetDriverName(), Is.EqualTo("Doe"));
}
```

```c#
public static class CarExtensionMethods
{
	public static string GetDriverName(this ICar car)
	{
		return car.DriverName;
	}
}
```

**Comment by stakx** [comment]
To be honest, I have no idea how Rhino Mocks might be doing this. As far as I can see, this is impossible to implement wothout resorting to platform specific facilities like the CLR's unmanaged profiler API, or perhaps the DLR. Feel free to send a PR if you know how to achieve this!

**Comment by stakx** [comment]
I had a quick look at how Rhino Mocks does this. It works roughly as follows:

```csharp
rCar.Expect(x => x.GetDriverName())
```

Rhino Mocks will put the mock (`rCar`) into a recording mode, then execute the action passed to it, then observe which method was last invoked on the mock. This way it knows to set up `ICar.DriverName` instead of `CarExtensionMethods.GetDriverName`.

```
.Returns("Doe");
```

Sets up the discovered proxy method's return value.

There are also parts in Moq 4 that work with a recorder-like mode (notably, when you use `SetupSet`), but it's fairly brittle. The feature is also rather brittle in Rhino Mocks. It works for very simple extension methods, but see what happens if it's changed just a little bit:

```csharp
public static string GetDriverName(this ICar car)
{
    Debug.WriteLine(string.Format("Getting driver name of car '{0}'...", car.Id));
    // ^ add just one additional access of a property of `car`
    return car.DriverName;
}
```

Now your Rhino Mock setup will no longer work.

In my opinion, adding Rhino Mocks' very brittle "ability" to setup extension methods to Moq would be a bad idea. While it might be useful in a few use cases, it would also try to pretend that extension methods *can* be mocked, potentially leading to a whole host of bug reports and feature requests that are impossible to fulfill. Better to admit upfront that extension methods, like any other non-virtual or sealed method, simply cannot be mocked.

**Comment by stakx** [comment]
@FireEmerald - Any thoughts on the above? How shall we proceed with this issue?

**Comment by FireEmerald** [comment]
On the one hand i agree that this functionality could cause misunderstandings of what is _mockable_ and what isn't. On the other hand if MOQ already has a _recorder-like mode_, it would be a nice to have feature due to the fact that there are usecases like chained extension methods which operate on simple properties of a class.

The functionality could be (perhaps) added via an additional nuget package. A extra package would ensure that the developer is automatically informed about the limited scope of this feature. Choosing a name like _Moq.LimitedExtensionSupport_ and a short readme would be enought to keep bug reports away.

**Comment by stakx** [comment]
> extension methods which operate on simple properties of a class

If you already have that knowledge about the extension methods, then I would suggest you just set up those properties directly, instead of relying on a semi-broken mechanism in Moq (or any other library).

> if MOQ already has a recorder-like mode

It has such a mode, not because it's something good to have, but ultimately as a workaround for the fact that the C# compiler will refuse building LINQ expression trees (`Expression<...>`) from assignments (see `SetupSet` et al.). It would be the wrong direction, IMO, to use that mode for even more things, when we should really want to get rid of it completely.

> The functionality could be (perhaps) added via an additional nuget package.

Yes, that might indeed be an option. It would require Moq to expose a few additional mock introspection bits. Reopening #569 might be a start. Your best bet though is Moq 5 (https://github.com/moq/moq) which will have much improved introspection support upon which extensions can be built.

**Comment by stakx** [comment]
I'm going to close this. Adding direct support for mocking extension methods won't happen. Regarding an additional NuGet package, it could be built on top of something like e.g. #569 (i.e. the ability to inspect invocations that happened on a mock). However, Moq's "recorder-like mode" (internally called `FluentMockContext`) as it is today should not be exposed, it simply isn't polished enough to become part of the public API. So I suggest you subscribe to #560 / #569.
