### ISSUE TITLE
mock.VerifySet exception after SetupSet

### ISSUE THREAD

**Issue by alisonniudehen** [moq/moq4#644]
// expects an invocation to set the value to "foo"
mock.SetupSet(foo => foo.Name = "foo");

// or verify the setter directly
mock.VerifySet(foo => foo.Name = "foo");

**Comment by stakx** [comment]
@alisonniudehen - Could you please elaborate a little? What is this issue about?

**Comment by alisonniudehen** [comment]
Hello,


thanks, I'm learning Moq now. I tried this below, it is failed.

It should pass, right?


use assumptions of this page

https://github.com/moq/moq4/wiki/Quickstart


[cid:e400f9a2-efe1-4851-a915-7dc4c8d25026]

Kind regards,


Alison Niu
0212991720


________________________________
发件人: stakx <notifications@github.com>
发送时间: 2018年7月19日 1:45
收件人: moq/moq4
抄送: alisonniudehen; Mention
主题: Re: [moq/moq4] mock.VerifySet exception after SetupSet (#644)


@alisonniudehen<https://github.com/alisonniudehen> - Could you please elaborate a little? What is this issue about?

―

**Comment by stakx** [comment]
> I tried this below, it is failed. It should pass, right?

Hard to say without seeing your code...

(PS: This issue tracker is mainly for bug reports and feature requests.)

**Comment by alisonniudehen** [comment]
use assumptions of this page
https://github.com/moq/moq4/wiki/Quickstart
code is just this:
var mock = new Mock<IFoo>();
mock.SetupSet(foo => foo.Name = "foo"); 
mock.VerifySet(foo => foo.Name = "foo");

so I think VerifySet has issue.

**Comment by stakx** [comment]
I see. You appear to have a misunderstanding about what these two calls do.

```csharp
mock.SetupSet(foo => foo.Name = "foo");
```

This sets up an expectation that the mock object's `Name` property will be set to `"foo"`.

Note that this does *not* set the `Name` property!

```csharp
mock.VerifySet(foo => foo.Name = "foo");
```

This checks whether the mock object's `Name` property was set to `"foo"` at least once. If not, it'll throw a `MockException`.

So as you can see, this code throws because you're never actually setting the property; you're only setting up the mock to expect this to happen, and checking whether it happened.

Further, unless you're using a strict mock (`MockBehavior.Strict`, which isn't the default behavior) calling `SetupSet` without having it immediately followed by `Callback`, `Throws`, etc. is not necessary. Mocks with loose behavior (the default) will allow any and all invocations, so unless you want to configure the mock's "reaction" to the setter invocation you don't need to explicitly set up the expectation at all.

**Comment by stakx** [comment]
Closing this, since there's nothing to be done at Moq's end. If you have any further questions about this, please feel free to ask here.
