### ISSUE TITLE
Counting number of call method before callback raise

### ISSUE THREAD

**Issue by iremezoff** [moq/moq4#65]
Why counting number of call mock method is realized after callback raise?
I perform following code for working imitation:

mock.Verify(m=>m.Execute()).Callback(()=>{Thread.Sleep(1000)}); // work imitations

But number of Execute method calls is changed after imitation have been completed.
Thanks.

ps: sorry, my English is very bad

**Comment by stakx** [comment]
Hi @iremezoff, it has been a long time since you asked this question. If you are still interested in an answer, please report back briefly. (In that case, it would be good to know a little more about what the exact problem with Moq is here.)

If you do not report back in a few days' time, I will close this issue.
