### ISSUE TITLE
`Verify` can create setups that causes a subsequent `VerifyAll` to fail

### ISSUE THREAD

**Issue by stakx** [moq/moq4#699]
### Reproduction code:

```csharp
public interface IX
{
    IX X { get; }
}

var mock = new Mock<IX>();
mock.Verify(m => m.X.X, Times.Never);
mock.VerifyAll();
```

### Actual behavior:

`VerifyAll` throws a `MockException` with message:

```
The following setups on mock 'Mock<IX:00000001>' were not matched:
IX mock => mock.X
```

### Expected behavior:

All verification steps should pass because there are no invocations nor any setups.

**Comment by lepijohnny** [comment]
There are more cases affected by this one as well. I would like to share them as they are, IMO, all related with the way how `FluentMockVisitor` unfold fluent expression into inner mocks with setup even though we actually do `Verify` but not `Setup`. It seems that `Verify` using fluent expression add (unexpected) side effects.

## 1. MochBehaviour.Strict has been avoided

### Reproduction code:

```
public interface IX
{
    IX X { get; }
}

var mock = new Mock<IX>(MockBehavior.Strict);
mock.Verify(m => m.X.X, Times.Never);
_ = mock.Object.X;
```

### Actual behaviour

No exception

### Expected behavior

`MockException` has been thrown as there is no setup for `m.X`

## 2. It is possible to invoke method\property without proper setup

### Reproduction code:

```
public interface IX
{
    IX X { get; }
}

var mock = new Mock<IX>();
mock.Verify(m => m.X.X, Times.Never);
_ = mock.Object.X.X;
```

### Actual behaviour

No exception

### Expected behavior

`NullReferenceException` has been thrown because we didn't setup return value for `IX` and it should be null.

**Comment by lepijohnny** [comment]
@stakx - `FluentMockVisitor` translate the fluent expression the same way, it doesn't matter if it is `Setup` or `Verify`. It will always, if inner mock is not there, create one, `SetupAllProperties` and add the `Setup`. This could lead to pollution of the mock and this vague behavior. What would be drawback of introducing additional info and passing it to `FluentMockVisitor` in order to avoid setup at all if verify is invoked?

**Comment by stakx** [comment]
@lepijohnny - I am in the process of re-architecting the way how such setups are performed internally. Once I'm done with that, `FluentMockVisitor` will likely no longer be needed at all. ;-)

(I should probably mark this and some other issues as "assigned to myself" so others know that a bugfix is already being prepared.)

**Comment by lepijohnny** [comment]
Sure, makes sense :+1:

**Comment by stakx** [comment]
@lepijohnny - Those bugs are gone now. I mentioned you in the changelog entry as you kindly provided a lot more test cases than I originally thought of; they've made it into the code base ([here](https://github.com/moq/moq4/blob/4e652a0ab3210d7b5794682a78198aa5cb2c7240/tests/Moq.Tests/VerifyFixture.cs#L1586-L1619)). Thanks for contributing those! :+1:

**Comment by lepijohnny** [comment]
@stakx - I appreciate that! Great job btw! +1
