### ISSUE TITLE
`net45` target causes major build issues in .NET Framework 4.7 projects

### ISSUE THREAD

**Issue by bassettb** [moq/moq4#719]
Moq should include a build target for .Net Framework 4.7.  This target would not have a dependency on System.ValueTuple.  The current 4.5 target causes major build issues in Framework 4.7 projects.

**Comment by stakx** [comment]
> The current 4.5 target causes major build issues in Framework 4.7 projects.

Interesting that noone reported any major issues up until now. Could you please explain in some more detail just what those issues are?

(P.S.: We've already had several issues asking for certain targets and it's being considered, so I will likely close this issue as a duplicate.)

**Comment by bassettb** [comment]
The warning is below.  It could not be resolved with a binding redirect or by adding the latest System.ValueTuple nuget to our projects.   `warning MSB3258: The primary reference "myproject.dll" could not be resolved because it has an indirect dependency on the .NET Framework assembly "System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" which has a higher version "4.0.3.0" than the version "4.0.2.0" in the current target framework.`

**Comment by stakx** [comment]
Must be something with your specific setup. Make sure you have the latest versions of everything (VS, NuGet, .NET Framework). It might also help to use `<PackageReference>` instead of `packages.config`. If you're using the old `.csproj` format, make sure you use `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>`.

Finally, please note that this type of problem cannot be fixed for everyone on Moq's side. It has to be fixed on the .NET & tooling side. The [`netfx-compat`-tagged issues in `dotnet/standard`](https://github.com/dotnet/standard/issues?q=is%3Aissue+is%3Aopen+label%3Anetfx-compat) are a testament to how widespread assembly versioning problems have become on the .NET Framework. [This post by Immo Landwerth (MSFT)](https://github.com/dotnet/standard/issues/481) is also a nice write-up although not directly related to `net45` vs `net47`.

Btw. here's a small C# project which compiles just fine (using VS 15.8.8 or MSBuild 15.8.169.51996) , without any warnings or errors. Feel free to use it as a starting point to track down & fix your versioning issue.

#### `.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.10.0" />
  </ItemGroup>

</Project>
```

#### `.cs`:

```csharp
using Moq;

public interface IMockable
{
    (bool success, string message) TryGetMessage();
}

class Program
{
    static void Main()
    {
        var (success, message) = Mock.Of<IMockable>().TryGetMessage();
    }
}
```

Closing as off-topic (versioning conflicts have come to be so frequent on the .NET Framework these days that unfortunately everyone needs to understand and learn how to deal with them), and as a duplicate (like I wrote above, additional NuGet targets are already under consideration &mdash; though to be honest `net47` is not on the list; `net471` or `net472`, perhaps).

**Comment by bassettb** [comment]
That's disappointing.  Our solution has 90 projects and uses 30-40 nuget packages.  We still use many non-nuget DLLs.  But we aren't unique.  Not every project out there is created perfectly clean like your example.  Many company's projects are slowly migrating from pre-nuget days using Framework to a future goal of using nuget and netstandard.  And along the way, they have a lot of challenges with package dependencies and tooling issues.  I'm sure there are many other users who, like us, can't use the latest version of moq because of these errors.  Ideally, a nuget package has few/no dependencies.
So it's easy to say 'this is Microsoft's problem'.  But you could solve it for a lot of people with a very small change in your code and allow wider adoption of your latest version.

**Comment by stakx** [comment]
Of course not every code base is as pristine as the little example I posted above. I posted it only to demonstrate that the claim, _"the current 4.5 target causes major build issues in Framework 4.7 projects"_ simply doesn't hold true in general. I am suggesting that if things don't work in your case, there must be some other factor involved, and it is important to know what that is before we blindly apply a fix.

I am not going to introduce a `net47` target on blind faith that it will magically solve versioning issues for "a lot of people". First, I want to understand what *exactly* can go wrong. If you can post a small solution that reproduces the issue you're seeing, then I'm happy to look into it.

**Comment by stakx** [comment]
@bassettb - I changed Moq such that it no longer needs to depend on `System.ValueTuple` at all... which appears to be the NuGet dependency that causes you problems. Will this help you?

**Comment by stakx** [comment]
@bassettb - I just pushed Moq 4.10.1 to NuGet. This version no longer depends on System.ValueTuple, and dependencies o n System.* NuGet packages have been upgraded to the latest versions. Consider giving it a try.
