### ISSUE TITLE
Mock virtual methods in base classes

### ISSUE THREAD

**Issue by WistfulWolf** [moq/moq4#724]
Hi,
I'm trying to mock a virtual method of the base class using partial mocks. The problem arises when I need to mock an overridden method. The example below should explain it better.

Base class
```
public class SignInManager
{
    public virtual Task<SignInStatus> PasswordSignInAsync(string userName, string password);
}
```

Extension
```
public class AppSignInManager
{
    public override async Task<SignInStatus> PasswordSignInAsync(string userName, string password)
    {
        SignInStatus signInStatus = await base.PasswordSignInAsync(userName, password);

        DoStuffBasedOnSignInStatus();

        return signInStatus;
    }
}
```

Mock (AAA-style)
```
var mock = new Mock<AppSignInManager>() { CallBase = true };
mock
    .Setup(s => s.PasswordSignInAsync(It.IsAny<string>(), It.IsAny<string>()))
    .Returns(Task.FromResult(signInStatus));

mock.Object.PasswordSignInAsync(String.Empty, String.Empty);

mock.Verify(v => v.DoStuffBasedOnSignInStatus(), Times.Once);

```

My expectations are DoStuffBasedOnSignInStatus is called but actually it isn't.
How can I setup mock for base method (and not for the actual method which I test)? Any help is much appreciated.

**Comment by stakx** [comment]
@WistfulWolf - Setting `CallBase = true` on the mock only has an effect for methods that have no setup at all. Since you're setting up `PasswordSignInAsync`, `CallBase = true` no longer takes effect for that method.

There's also a method-level `.CallBase()` with slightly different semantics: it's used as an alternative to `.Returns()`. The return value gets determined by the base method implementation.

Then there's `.Callback()`, which allows you to specify behavior for the mocked method.

You can combine `.CallBase()` and `.Callback()` as follows:

```csharp
public class Base
{
	public virtual Task<string> GetValueAsync()
	{
		Console.WriteLine("Base.Do invoked");
		return Task.FromResult("Result produced by Base.GetValueAsync");
	}
}

class Program
{
	static async Task Main()
	{
		var mock = new Mock<Base>();
		mock.Setup(m => m.GetValueAsync())
			.Callback(() => Console.WriteLine("Before call to base"))
			.CallBase()
			.Callback(() => Console.WriteLine("After call to base"));

		var value = await mock.Object.GetValueAsync();
		Console.WriteLine("Value: " + value);
	}
}
```

This will print:

```
Before call to base
Base.Do invoked
After call to base
Value: Result produced by Base.GetValueAsync
```

Hopefully, you can adapt this example to your own scenario.

What Moq currently doesn't allow is calling the base method because of its side effects, but then returning a different value with `.Returns`.

**Comment by WistfulWolf** [comment]
@stakx thank you for your response! 
As I see it's impossible to check whether the base method's called using Verify to check parameters and number of times it's invoked.

```
public class Base
{
    public virtual Task<string> GetValueAsync(int inputParameter)
    {
    }
}

public class DerivativeFromBase : Base
{
    public override Task<string> GetValueAsync(int inputParameter)
    {
        int newParameter = DoWhateverINeed();

        return base.GetValueAsync(newParameter);
    }
}
```

Basically I need check that when I call GetValueAsync on instance of DerivativeFromBase class the GetValueAsync of Base is called and receives newParameter. But I don't really see any solution for this using `.CallBase()`.

**Comment by stakx** [comment]
@WistfulWolf - Imagine for a moment that you didn't have a mocking library available. How would you do what you want to do if you coded your mock manually? If you can't find a solution, then it's likely that Moq won't be of any help (because it really just automates what you'd otherwise have to do manually).

The best I can think of is to convert the relationship between `Base` and `DerivativeFromBase` from inheritance to composition. `Derivative` would then receive a `Base` object that it uses inside `GetValueAsync`&mdash;which allows you do swap it out with a `Mock<Base>`.

**Comment by WistfulWolf** [comment]
@stakx - I see your point. I raised this question because when I'd been looking for solution in the Internet I bumped into this [https://www.telerik.com/forums/how-to-mock-base-class-method]. Thus I thought that **Moq** might support this behaviour as well. Looks like JustMock uses different approach to mock methods in base classes. Anyway thank you for your time!

**Comment by stakx** [comment]
I see. I suspect that JustMock is using the CLR's profiling API in order to mock things like non-public, static, or sealed members. Moq is less powerful in that regard as it uses a different foundation.
