### ISSUE TITLE
Trouble building on OSX

### ISSUE THREAD

**Issue by Bungalow12** [moq/moq4#726]
I'm having trouble restoring NuGet packages:
```/Users/jonathanwills/Projects/moq4/src/Moq/Moq.csproj: Error NU1202: Package System.Reflection.TypeExtensions 4.4.0 is not compatible with net45 (.NETFramework,Version=v4.5). Package System.Reflection.TypeExtensions 4.4.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net46 (.NETFramework,Version=v4.6)
  - net461 (.NETFramework,Version=v4.6.1)
  - netcore50 (.NETCore,Version=v5.0)
  - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
  - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - netstandard1.5 (.NETStandard,Version=v1.5)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0) (NU1202) (Moq)```
Any idea what I can do to rectify this so I can use this on OSX?
Or do you have pre-built DLLs available anywhere I can reference?

**Comment by stakx** [comment]
Sorry, I don't understand your post at all. Are you trying to build Moq from source? If so, using what tools? (You'd probably need to have Mono installed in order to compile the `net45` target.) What does that list of targets above mean?

If you just want to use Moq, why not just use the **Moq** NuGet package? (If you just want DLLs, download the NuGet package from NUGet.org, rename it to a `.zip` file, then open it. You'll find the DLLs in the `lib/` folder.)

**Comment by Bungalow12** [comment]
Oh... Yeah I guess that makes a lot more sense. :/
Regardless there is no easy way I have found to build Moq from source on
OSX. So that would still be awesome if it was made easier.

**Comment by stakx** [comment]
@Bungalow12 - Well, would you be interested in looking into this? I can't be of much help there, as I don't have access to an Apple machine. I'm pretty sure that it would take a recent Mono installation because you'd need a set of .NET Framework 4.x reference assemblies to build against. I also suspect that the build process as a whole might have to be rewritten to make use of the `dotnet` toolchain (at the very least, `dotnet msbuild` instead of `msbuild`).

**Comment by stakx** [comment]
Hi @Bungalow12, just going through issues and saw this one has been idle for a while. Did you ever get around to look into Moq4 build script improvements for OSX? (If not, I suggest we close this issue for now. We can mark it as unresolved, and always open again in the future if we pick up that particular thread again.)

**Comment by Bungalow12** [comment]
It’s definitely a nice to have but hardly vital. I’ll close the issue.
