### ISSUE TITLE
Invocations.Clear() does not cause Verify to fail.

### ISSUE THREAD

**Issue by jchesshir** [moq/moq4#733]
If an expected function on a Mock is called and then Invocations.Clear() is called on the Mock object, it does not erase the record of the call.  Consequently, a call to a Verify function after the call to Invocations.Clear succeeds.  

I would expect the code to throw an error on the call to an error.
For example:

    try
    {
        Mock<ITest> mockTest = new Mock<ITest>(MockBehavior.Strict);
        mockTest.Setup(t => t.CallMe());
        mockTest.Object.CallMe();
        mockTest.VerifyAll(); // Succeeds as expected.

        mockTest.Invocations.Clear();
        mockTest.VerifyAll(); // Still succeeds

        Assert.Fail("Code should not have reached this point.");
    }
    catch (MockException e)
    {
        Console.WriteLine("Expected exception thrown.");
    }
    catch (AssertFailedException ex)
    {
        Console.WriteLine("Code got to the last line of the try.");
    }

The above code generates the output:

    Code got to the last line of the try.

**Comment by stakx** [comment]
Thanks for reporting.

I'm in two minds about this. Consider this related example:

```csharp
class Toy
{
    public string Color { get; set; }
}

interface IPlayer
{
    void PlayWith(Toy toy);
}

var toy = new Toy { Color = "green" };

var player = new Mock<IPlayer>();
player.Setup(p => p.PlayWith(It.Is<Toy>(t => t.Color == "green"))).Verifiable();

player.Object.PlayWith(toy);
player.Verify();

toy.Color = "red";
player.Verify();
```

Should the second `Verify` succeed, or should it fail?

On the one hand, it should succeed because there *was* an invocation matching the setup expression (i.e. a green toy was being played with)--even when the toy is now no longer green.

On the other hand, it should fail because the setzp expression no longer matches viewed from a retrospective: The toy that was being played with is red at the time of verification, not green (as the setup requires).

In my opinion, the first interpretation makes more sense. Invocations are matched against setups at the time when the invocation happens, not when verification happens. There can be state changes between these two points in time, and there's simply no general means for `Verify` to travel back in time and undo those changes.

Back to your example, I agree that it is somewhat counterintuitive, but I think the same reasoning should apply here: Fact is that there *was* a call matching the setup, even if its traces have later been erased.

It's an arguable case, though.

**Comment by stakx** [comment]
@jchesshir - I've been expecting this issue to be raised eventually, thanks for reporting it. This is one of those not-so-clear-cut cases where it is not so clear, or up to personal interpretation, what should happen. However, there are reasons why `VerifyAll` works the way it does:

What `Verify` and `VerifyAll` do is to check whether all setups have been invoked at least once. (They only differ in which setups they look at, but that's irrelevant for this issue.)

You could say, `Verify[All]` should look at all currently recorded invocations and match them against the setups. (You appear to be expecting that this is what happens.)

On the other hand, you could also insist on the correctness of the above definition of `Verify[All]`: Your setup *has in actual fact* been matched by an earlier invocation&mdash;even though there is now no longer any record of that invocation&mdash;so it's only right that your second `VerifyAll` call still succeeds. (This is how Moq actually works.)

The problem with the first stance (i.e. matching the currently recorded invocations against the setups at the time of the `Verify[All]` call) is that it leads to problems when object state changes get involved. You'd no longer be able to do certain things. Consider this example:

```csharp
public class Toy
{
    public string Color { get; set; }
}

public interface IChild
{
    void PlayWith(Toy toy);
}

var child = new Mock<IChild>();
child.Setup(c => c.PlayWith(It.Is<Toy>(t => t.Color == "Red")));
child.Setup(c => c.PlayWith(It.Is<Toy>(t => t.Color == "Green")));

var chameleon = new Toy();

chameleon.Color = "Red";
child.Object.PlayWith(chameleon);

chameleon.Color = "Green";
child.Object.PlayWith(chameleon);

child.VerifyAll();
```

This only works because invocations are matched against the setups *at the time of the invocation*. If they were matched against setups at the time of the `VerifyAll` call, the first setup (for the child playing with a red toy) would fail.

**Comment by stakx** [comment]
> [...] and then Invocations.Clear() is called on the Mock object, it does not erase the record of the call.

What didn't occur to me in all of the above is that `Invocations.Clear()` simply doesn't erase traces of earlier calls thoroughly enough. It should be possible to "un-match" setups (but that'd technically be a breaking change).

**Comment by jchesshir** [comment]
Yes. That is my issue exactly. I'd like to be able to reuse the mock
objects for multiple tests. As it stands I have to create and initialize a
new mock for every test. That seems to make an unnecessarily resource
bloated test set.

While I can see how changing that behavior could be a breaking change, I've
trouble understanding the use case that would benefit from the current
functionality. Can you give me an example?

I suppose if there is a valid case, you could just create another function
or an overload to clear the invocation count in addition to/instead of what
it currently does.

Thank you!

**Comment by stakx** [comment]
> I've trouble understanding the use case that would benefit from the current functionality. 

I believe that the ability to clear the set of recorded invocations was introduced as a memory optimization. When you have a test that requires a very large number of invocations on your mock, these get recorded (regardless of whether your test actually requires that for later assertions or not), and that can eventually cause a `OutOfMemoryException`. I suspect that being able to remove invocation records was a cheap (if somewhat inelegant) way around that problem for someone in the past.

I think what you're requesting might actually improve the logical consistency of Moq's API overall, even given the breaking change. I'll give it some more thought.

**Comment by jchesshir** [comment]
That makes sense.  Thank you again for considering the change.

**Comment by stakx** [comment]
Will do. One last thing I forgot to mention earlier:


> I'd like to be able to reuse the mock objects for multiple tests. As it stands I have to create and initialize a new mock for every test.

I suspect that the conventional wisdom of the unit testing community would say that creating new mocks per test is actually a good thing, as it prevents state changes of one test from accidentally "bleeding over" into other tests, thus keeping them independent.

That being said, I'll still look into the request you've made as it still seems like a sensible change.

**Comment by stakx** [comment]
Smallish update, I asked kzu about this [in the Moq Gitter chat](https://gitter.im/moq/moq?at=5c2f88068dafa715c73ffb44) to make sure we'd have good compat with Moq v5; seems we're good to go & ready to implement the change discussed above.
