### ISSUE TITLE
Add .Net Standard 2.0 target

### ISSUE THREAD

**Issue by vhatsura** [moq/moq4#742]
According to [Open-source library guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting) it would be good to target .Net Standard 2.0 to benefit from having a smaller package graph.

I would appreciate to help with it.

**Comment by OskarKlintrot** [comment]
https://github.com/moq/moq4/issues/630

**Comment by stakx** [comment]
@vhatsura - First of all, many apologies for the delayed response. I haven't quite been able to keep up with my open-source duties due to my daytime work. :)

The first thing that will have to happen in the Moq codebase will be a cleanup of the conditional compilation symbols (`DESKTOP`, `NETCORE`, `FEATURE_CAS`, `FEATURE_CODEDOM`, `FEATURE_COM`, `FEATURE_SERIALIZATION`, etc.). The code portions that they guard need to be freshly mapped to the various new targets.

For example, the `DESKTOP` symbol more or less designates the .NET Framework 4.x target, while `NETCORE` symbol is used to signify the .NET Standard 1.x target. Already the names of those symbols don't fit very well. And they will fit even less when you consider that on .NET Standard 2.x, code currently guarded by `DESKTOP` would actually run just fine.

So what needs to happen here (IMO) is that `DESKTOP` and `NETCORE` should be replaced with something more akin to "feature flag" symbols like `FEATURE_SERIALIZATION`. Then for each supported target we need to determine whether that feature is available.

You're welcome to help with this refactoring! If you'd like to help, please briefly let me know so we can make a definite plan.
