### ISSUE TITLE
Add support for detecting unused setups

### ISSUE THREAD

**Issue by dfev77** [moq/moq4#747]
After a while there is a big chance (especially when dealing with legacy code) to have tons of mock setups that are actually not used.
It would be nice to be able to spot such case in order to cleanup the code.

An option would be to allow the test(s) to fail if there were any mocks which had setups that were not called (at the point where the mock gets out of scope)

**Comment by stakx** [comment]
> An option would be to allow the test(s) to fail if there were any mocks which had setups that were not called

If you get your mocks from a `MockRepository` instead of `new`-ing them up, that should be trivial:

```csharp
mockRepository.VerifyAll();
```
> at the point where the mock gets out of scope

.NET does not have deterministic resource cleanup like that (we'd need something like C++'s RAII idiom) so that is impossible to do. The closest thing in .NET is the `IDisposable` protocol, but it's far too late in the game to make `Mock<T>` implement `IDisposable`.

In all honesty, if your tests get so large that you no longer know what mocks and setups you have, then *that* is the problem to solve; putting a bandaid on it (in the form of a library feature) is not a good way to deal with this (IMO).

That being said, this problem might be tackled with a Roslyn analyzer.

**Comment by stakx** [comment]
@dfev77, any thoughts about the above reply? Otherwise I'll close this issue in a couple of days, since there's not much that can be done (short of rigging setups with a `TimebombException` that goes off when the setup is not invoked for a set amount of time&mdash;and I don't think that would make for a very good feature :-D).

**Comment by stakx** [comment]
Closing due to a lack of feedback (and lack of implementation options). If you'd like to further discuss this or make further suggesrions, feel free to post here -- we can always reopen the issue.
