### ISSUE TITLE
Modify object captured by invocation impact the `Verify`

### ISSUE THREAD

**Issue by lepijohnny** [moq/moq4#756]
Hi,

I found one strange behavior. The problem is that underlying invocation has been changed. Then 

This is reproduction code...

```
public class Foo
{
	public bool AmIRealFoo { get; set; }
}

public interface IBar
{
	void Bar(Foo f);
}

var mock = new Mock<IBar>();

var foo = new Foo{AmIRealFoo = true};
mock.Object.Bar(foo);
foo.AmIRealFoo = false;

mock.Verify(m => m.Bar(It.Is<Foo>(f => f.AmIRealFoo)), Times.Once); //fails
mock.VerifyAll(); //pass
```

Expected behavior is that both `VerifyAll` and `Verify` pass.

**Comment by stakx** [comment]
This is a misunderstanding on your part. Moq does the right thing here.

Arguments are compared using `Equals`. Because `Foo` is a reference type, all that gets recorded for your `mock.Object.Bar(foo);` call is that `Bar` was called with the `foo` object. The state of `foo` is not automatically captured.

Your `mock.Verify` fails because verification looks at all invocations that happened, and passes each through the criteria given. So it takes the recorded call to `Bar(foo)` and passes the `foo` instance through `It.Is<Foo>(f => f.AmIRealFoo)`. Because `foo.AmIRealFoo` is `false` by that time, the criterion is not satisfied and that invocation is not matched to your verification expression.

`mock.VerifyAll` succeeds because it checks whether all setups on `mock` have been invoked at least once. Since there are no setups at all, there is no failure here and the verification succeeds.

**Comment by lepijohnny** [comment]
@stakx - It perfectly makes sense if you don't have `setup` but actually it will fail even if you have `setup` as, you explained that as well, `Verify` acts purely on invocation and `VerifyAll` acts on setups.

```
var mock = new Mock<IBar>();
mock.Setup(m => m.Bar(It.IsAny<Foo>()));
var foo = new Foo{AmIRealFoo = true};
mock.Object.Bar(foo);
foo.AmIRealFoo = false;

mock.Verify(m => m.Bar(It.Is<Foo>(f => f.AmIRealFoo)), Times.Once); //fails
mock.VerifyAll(); //pass
```

Thanks.
