### ISSUE TITLE
InSequence only works with MockBehavior.Strict and exception thrown is misleading

### ISSUE THREAD

**Issue by thulani-chivandikwa** [moq/moq4#804]
InSequence only works with MockBehavior.Strict (or I am failing to get it to work in Loose). When this works however the exception thrown is misleading.

Example:

```
            var mock = new Mock<Sample>(MockBehavior.Strict);
            var mockSequence = new MockSequence();
            mock.InSequence(mockSequence).Setup(x => x.A()).Returns("A");
            mock.InSequence(mockSequence).Setup(x => x.B()).Returns("B");

            mock.Object.B();
            mock.Object.A();
```

Exception says:

> Moq.MockException: 'Sample.B() invocation failed with mock behavior Strict.
> All invocations on the mock must have a corresponding setup.'

I would expect the exception to indicate that the invocation was not done in the correct order. Additionally I do not see why this only works with MockBehavior.Strict.

**Comment by stakx** [comment]
> ```csharp
> mock.InSequence(mockSequence).Setup(x => x.A()).Returns("A");
> mock.InSequence(mockSequence).Setup(x => x.B()).Returns("B");
> ```

This sets up the mock to expect two calls to `A`, then `B` (in that order).

### When the mock is a strict mock:

> ```csharp
> mock.Object.B();
> ```

You're calling `B()` first, but that does not match what the sequence setups expects at this time (it expects a call to `A()`). Therefore the sequence setup is not matched at all. Moq goes on looking for another setup that might match this call to `B()`, and doesn't find one. So it complains by saying that all invocations on a strict mock must have a setup.

This behavior is fully correct and should be expected.

### When the mock is a loose mock:

> ```csharp
> mock.Object.B();
> ```

You're calling `B()` first, but that does not match what the sequence setups expects at this time (it expects a call to `A()`). Therefore the sequence setup is not matched at all, and as there is no other setup that would match `B()`, and you're dealing with a loose mock, nothing happens for that call.

> ```csharp
> mock.Object.A();
> ```

This call matches what the sequence setup expects, so the setup is matched. It is now updated to expect the next call in line, `B()`.

If you're not verifying the setups by any call to `mock.Verify[All]()`, then nothing further happens.

If you *are* verifying the setups, or even just the second one for a call to `B()`, then you would expect verification to fail, as that setup has not been invoked.

This is strange behavior and somewhat unintuitive. It's a direct consequence of how Moq currently implements sequences: namely, in terms of conditional setups (`mock.When(...).Setup(...)`). All conditional setups are excluded during verification; that's why a `mock.VerifyAll()` won't throw despite the setup for `B()` not having been invoked.

### What can be done about this?

In the very short term, probably nothing. Moq sequences have been discussed before in the past (mostly in #21 and #75), and I think there is consensus that they're currently not a very mature feature. They could definitely use some work.

**Comment by thulani-chivandikwa** [comment]
Thanks for the detailed response @stakx, I do know now how this works behind the scenes. The last part in did as you mentioned is not intuitive but also understandable that in the short term this may not be actioned.

**Comment by stakx** [comment]
Closing this in favour of #75, which is already a little further ahead with some concrete proposals on how Moq sequences could be improved.
