### ISSUE TITLE
Setup with interpolated strings

### ISSUE THREAD

**Issue by Llujoo** [moq/moq4#821]
The following code does not work
`
moq.Setup(m => m.Get("something[{i}].Name")).Returns($"foo {i}");
`
I had to use this instead.
`
moq.Setup(m => m.Get("something[" + i + "].Name")).Returns($"foo {i}");
`

**Comment by stakx** [comment]
Are you sure you didn't just miss a `$` (see above, you have a regular `"..."` string instead of `$"..."` so obviously interpolation wouldn't happen).

**Comment by stakx** [comment]
The above being said, yes, it seems entirely likely that the workaround might still be needed since you're in an expression tree context. Generally speaking, you shouldn't be including computations in setup expressions that aren't necessary / strictly relevant for that setup.

**Comment by stakx** [comment]
Yes, `m.Get($"something[{i}].Name")` is really equivalent to `m.Get(string.Format("something[{0}].Name", i))`. Unlike `m.Get("something[" + i + "].Name")`, the former will be lazily evaluated because it involves a function call as the argument. While using `$"..."` string interpolation should be supported, it'll lead to lazy evaluation, so if `i` is an iteration variable, for example, by the time your setups get invoked, `i` will have the final iteration value and that's what the setup(s) will use.

**Comment by Llujoo** [comment]
Interesting. Thank you for your response.
