### ISSUE TITLE
How to mock an interface that is serialized by Newtonsoft.json ?

### ISSUE THREAD

**Issue by Anthony-Breneliere** [moq/moq4#822]
I mock an interface from which the object is serialized by the tested code by the Newtonsoft JsonConvert.SerializeObject.

The serializer throws an exception with the following error:

Newtonsoft.Json.JsonSerializationException : Self referencing loop detected for property 'Object' with type 'Castle.Proxies.IActionProxy'. Path 'Mock'.

Newtonsoft tries to to serialized the proxy object IActionProxy, that has a property Mock that loops on that serialized object.

Curisouly changing serializer options
ReferenceLoopHandling = ReferenceLoopHandling.Serialize ( ot Ignore)
PreserveReferencesHandling = PreserveReferencesHandling.All
does not solve the problem, serialization: become infinite

Thank you for solving this issue, I would be happy to have a way using Moq in that case

**Comment by stakx** [comment]
@Anthony-Breneliere, please post a minimally complete code example that reproduces the issue you're describing.

**Comment by Anthony-Breneliere** [comment]
Of course, here is a sample:
```
Mock<IAction> _actionMock = new Mock<IAction>().SetupAllProperties();
Newtonsoft.Json.JsonConvert.SerializeObject( _actionMock.Object );  // JsonSerializationException (this line is in a method which i'm not responsible of )

```

**Comment by stakx** [comment]
I cannot reproduce the issue you're reporting. I am running the following program using Moq 4.10.1 and Newtonsoft.Json 12.0.2 (and I've even tried with all major versions down to 6.x).

```csharp
public interface IAction
{
	string Description { get; }
	object Argument { get; }
}

var actionMock = new Mock<IAction>().SetupAllProperties();
Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(actionMock.Object));
```

Output:

```
{
  "__interceptors": [
    {}
  ],
  "__target": null,
  "__interfaces": [
    "Moq.IMocked, Moq, Version=4.10.0.0, Culture=neutral, PublicKeyToken=69f491c39445e920",
    "Moq.IMocked`1[[IAction, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Moq, Version=4.10.0.0, Culture=neutral, PublicKeyToken=69f491c39445e920"
  ],
  "__baseType": "Moq.Internals.InterfaceProxy, Moq, Version=4.10.0.0, Culture=neutral, PublicKeyToken=69f491c39445e920",
  "__proxyGenerationOptions": {
    "hook": {},
    "selector": null,
    "mixins": null,
    "baseTypeForInterfaceProxy.AssemblyQualifiedName": "Moq.Internals.InterfaceProxy, Moq, Version=4.10.0.0, Culture=neutral, PublicKeyToken=69f491c39445e920"
  },
  "__proxyTypeId": "interface.without.target",
  "__targetFieldType": "System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
  "__theInterface": "IAction, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
}
```

Incidentally, the above output shows that serializing a mock probably won't do what you wanted it to do. Allow me a few remarks:

* I am not certain whether attempting to serialize an interface ever makes much sense. Interfaces represent contracts, not data objects; you'll never know what you'll get because the serialization is tied to the implementing class. (That's probably why .NET won't allow you to mark an interface type as `[Serializable]`.)

* Just what should a mock's serialization look like? The possibilities can range from fairly straightforward (e.g. when you've used `SetupAllProperties`, perhaps you want the property values to be included in the serialization output) to not-so-clear-cut (e.g. what should happen for a property with a sequence setup behind it that throws?).

What exactly did you need to serialize your mocked object for?

**Comment by Anthony-Breneliere** [comment]
I tried your example with same version (moq 4.10.1 and Newtonsoft.Json 12.0.2).

There is no issue with a Framework .NET 4.7.2 Console App, but I reproduce the bug with .Net Core 2.2 (same Console App)!

For your questions: I just use a library for what it does and that is a kind of project you wouldn't want to depend on it. I did not code it and I don't know why it is serialized, maybe just logs. It would have been nicer to have a POCO project but there is not. That is not the interface that is serialized but the implementation. I just need to mock the interface to test my code.

**Comment by stakx** [comment]
OK, since you don't actually care about the serialization itself, and just want to get things to execute without an error, I suggest you try the following change:

```diff
 var actionMock = new Mock<IAction>().SetupAllProperties();
+_ = actionMock.As<ISerializable>();
 Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(actionMock.Object, Formatting.Indented));
```

Letting your mock implement `ISerializable` (as a no-op) appears to quiet down Newtonsoft.Json.

Beyond that, I'd say the problem here lies with more with Newtonsoft.Json than with Moq, since Newtonsoft.Json obviously functions differently depending on what platform you're running your code on. Perhaps check up with that library what that is the case.
