### ISSUE TITLE
Moq internal call list is mutable

### ISSUE THREAD

**Issue by Deathofdemigod** [moq/moq4#851]
I expect internal call list to be immuteable and following example to work.

``
	<Project Sdk="Microsoft.NET.Sdk">

	  <PropertyGroup>
		<TargetFramework>netcoreapp2.2</TargetFramework>
	  </PropertyGroup>

	  <ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.1.1" />
		<PackageReference Include="Microsoft.UnitTestFramework.Extensions" Version="2.0.0" />
		<PackageReference Include="Moq" Version="4.12.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="1.4.0" />
		<PackageReference Include="MSTest.TestFramework" Version="1.4.0" />
	  </ItemGroup>

	</Project>
`
     using Microsoft.VisualStudio.TestTools.UnitTesting;
     using Moq;

     namespace MoqExample
    {

    [TestClass]
    public class MoqTestClass
    {
        private class RefParam
        {
            public string SomeString { get; set; }
        }

        private interface IServiceToMock
        {
            void MethodToVerify(RefParam rp);
        }

        private class TestService2
        {
            private readonly IServiceToMock _ts;
            public TestService2(IServiceToMock ts)
            {
                _ts = ts;
            }

            public void TestMethod2(RefParam rp)
            {
                switch (rp.SomeString)
                {
                    case "a":
                        _ts.MethodToVerify(rp);
                        break;
                    case "b":
                        rp.SomeString = "c";
                        _ts.MethodToVerify(rp);
                        break;
                }
            }
        }

        readonly Mock<IServiceToMock> _mock = new Mock<IServiceToMock>();
        private TestService2 _sut;

        [TestInitialize]
        public void TestInitialize()
        {
            _sut = new TestService2(_mock.Object);
        }

        [TestMethod]
        public void MutableInvocationList()
        {
            var sequence = new MockSequence();
            _mock.InSequence(sequence).Setup(mth => mth.MethodToVerify(It.Is<RefParam>(x => x.SomeString == "a")));
            _mock.InSequence(sequence).Setup(mth => mth.MethodToVerify(It.Is<RefParam>(x => x.SomeString == "c")));
           
            var rp = new RefParam{SomeString = "a"};
            _sut.TestMethod2(rp);
            rp.SomeString = "b";
            _sut.TestMethod2(rp);

            _mock.Verify(x => x.MethodToVerify(It.IsAny<RefParam>()), Times.Exactly(2));
            _mock.Verify(x => x.MethodToVerify(It.Is<RefParam>(r => r.SomeString == "c")), Times.Once);
            _mock.Verify(x=>x.MethodToVerify(It.Is<RefParam>(r => r.SomeString == "a")), Times.Once);
        }
    }
}

`

**Comment by stakx** [comment]
If this issue is about the fact that Moq doesn't "snapshot" the exact state of reference-typed arguments, but only captures the object reference: You're not the first one to expect Moq to do just that, yet to implement this would be prohibitively expensive as it would require Moq to perform deep cloning of each and every argument. Even if we were going to do this, I'm not sure that it would even be possible in all cases, as one would possibly have to bypass involved types' constructors (as happens e.g. during deserialization).

Moq observes the regular behavior of types: for value-typed arguments, it copies the value; for reference-typed arguments, it copies the reference (i.e. the normal behaviour of assignment in .NET). When matching arguments, it likewise observes the normal .NET behavior by simply comparing two values using `object.Equals`. All of this is by design and very unlikely to change.
