### ISSUE TITLE
Support || and ?: in Mock.Of

### ISSUE THREAD

**Issue by ashmind** [moq/moq4#86]
I think the `x || a` and `x ? a : b` should be supported in `Mock.Of` as long as `x` can be calculated immediately when mock is set up.

Example:

```
Mock.Of<INode>(
    m => m.GetProperty("p1").Value == p1
      && (p2 == null || m.GetProperty("p2").Value == p2)
      && (p3 == null || m.GetProperty("p3").Value == p3)
)
```

Here `p1`, `p2` and `p3` are external variables/parameters.
What should happen is if `p2 == null`, `m.GetProperty("p2")` is not mocked at all.

**Comment by stakx** [comment]
I am not certain how well this fits the idea of `Mock.Of<T>`, which is that it returns a mock that satisfies the given condition. My own interpretation is that this condition should hold true over the entire lifetime of the created mock, not just at the one point in time when the mock gets created.

Viewed from this angle (the condition being true during the mock's entire lifetime), your usage example becomes difficult to interpret. How can a method be mocked at one time, and then it's not mocked anymore a little later because an external variable changes? How would mock verification be expected to work for such a there-then-gone-then-back-again method?

**Comment by stakx** [comment]
Closing this. I believe this feature would introduce unneeded complexity that will canb e avoided.
