### ISSUE TITLE
Updating .net version dependency from 4.5

### ISSUE THREAD

**Issue by james1301** [moq/moq4#866]
When are you updating .net version dependency from 4.5? This version is no longer supported my Microsoft, we have recently updated to the latest .net as there is no real loss of OS support.

This may reduce the need for dependency on other nuget packages like Tasks.Extensions.

**Comment by stakx** [comment]
> When are you updating .net version dependency from 4.5?

Most likely at the same time when we add a target for .NET Standard 2.1 (which isn't available just yet); i.e. sometime later this year.

> This version is no longer supported my Microsoft [...]

I'm aware of that, but how exactly is this a problem in this case? Your own project (the one referencing Moq) can simply target a higher .NET Framework version, then NuGet will resolve packages relative to that.

> This may reduce the need for dependency on other nuget packages like Tasks.Extensions.

I don't see how: Moq only has two dependencies: Castle.Core, and System.Threading.Tasks.Extensions. The latter has a dependency on System.Runtime.CompilerServices.Unsafe, regardless of what frameworks Moq targets.

I'm very much aware of the demand for fewer package dependencies, but our `net45` target really isn't the main problem. What's much worse is that we're relying on `Castle.Core` which for .NET Standard is still at `netstandard1.x` target, which causes tons of unwanted transitive dependencies. (We're waiting on .NET Standard 2.1 to arrive, see https://github.com/castleproject/Core/issues/407.) That's why Moq has a `net45` target at all... to avoid these dependencies when your own project targets the .NET Framework. If it weren't for that, Moq would perhaps be a .NET Standard 2.x-only package by now.

**Comment by james1301** [comment]
Fair enough. I was just thinking that Tasks.Extensions was included in a later .net like valuetuples are so then it wouldn't require the additional nugets. But I don't think that does work the same does it?

**Comment by stakx** [comment]
> I was just thinking that Tasks.Extensions was included in a later .net like valuetuples are so then it wouldn't require the additional nugets.

No, `ValueTask<>` is not included in the BCL of later .NET Framework versions. Suppose it were included in .NET 4.7.2's BCL, your project is targeting .NET 4.7.2 and referencing Moq. You'd get type ambiguities because `ValueTask<>` would now be defined several times (once by the BCL, once by the NuGet package brought in by Moq). In order to prevent this, Microsoft would typically add an empty `net472` target to that NuGet package.

So, to conclude this, as far as I can see, updating Moq's target from `net45` to `net452` is not going to achieve anything at all regarding NuGet dependencies, regardless of whether your own project references `net45` or a later .NET Framework version.
