### ISSUE TITLE
Callback with specific object type fails when not after a Return

### ISSUE THREAD

**Issue by debslord** [moq/moq4#872]
Moq version 4.12.0

Callback for a method with multiple parameters when one is a specific object type throws the following error unless the Callback follows a Returns.

**_Message: Initialization method Project.Services.Tests.__Initialize threw exception. System.ArgumentException: Invalid callback. Setup on method with parameters (String,Object) cannot invoke callback with parameters (String,SpecficObjectType).._**

**EXPECTED OUTCOME**
Callback does not throw an error irrelevant as to whether you specify an object type, have multiple parameters or whether or not the Setup has a Returns configured. 

**ACTUAL OUTCOME**
It only works when there is one single specific object type parameter and when it follows a Returns - examples below.  

These setups get the above error:

```csharp
_mockService
     .Setup(x => x.SomeMethod(fakeString, It.IsAny<SpecficObjectType>()))
     .Callback<string, SpecficObjectType>((a, b) => _parameters = b);

_mockService
     .Setup(x => x.SomeMethod(fakeString, It.IsAny<SpecficObjectType>()))
     .Callback<string, SpecficObjectType>((a, b) => _parameters = b)
     .Returns(() => value);
```

These setups work:

```csharp
_mockService
     .Setup(x => x.SomeMethod(fakeString, It.IsAny<SpecficObjectType>()))
     .Returns(() => value)
     .Callback<string, SpecficObjectType>((a, b) => _parameters = b);

_mockService
     .Setup(x => x.SomeMethod(fakeString, It.IsAny<SpecficObjectType>()))
     .Callback<string, object>((a, b) => _parameters = (SpecficObjectType)b)
     .Returns(() => value);

_mockService
     .Setup(x => x.SomeMethod(It.IsAny<SpecficObjectType>()))
     .Callback<SpecficObjectType>((a) => _parameters = a);
```

**Comment by stakx** [comment]
Your callback's parameter types should match the parameter types of the method you're setting up, so some of the errors you're seeing are due to that (i.e. a mistake on your part).

However, this case looks strange:

> ```csharp
> _mockService
>      .Setup(x => x.SomeMethod(fakeString, It.IsAny<SpecficObjectType>()))
>      .Returns(() => value)
>      .Callback<string, SpecficObjectType>((a, b) => _parameters = b);
> ```

I suspect that the above shouldn't work, either.

I'll take a closer look sometime during the next few days.

**Comment by stakx** [comment]
I am sure that's not what you intended with this issue, but the solution here is to make post-`Returns` callback delegate validation more strict so we no longer have an inconsistency.

Like I wrote above, if you have a method with parameter list, say, `(string, object)`, you cannot specify a callback delegate with parameter list `(string, string)` because you'd be coercing the second argument to a type that it may not be compatible with. While the `It.IsAny<string>()` argument matcher protects against this problem at runtime, it doesn't help a bit at compile time... and reliance on static typing is one of Moq's [declared goals](https://github.com/moq/moq4/blob/master/README.md#features-at-a-glance).

**Comment by debslord** [comment]
I will update my code my side for more consistency.  However for your reference please find the following zipped example of the two setups one passes the tests and one does not.  If you required an example of the issue.

[MoqDemo.zip](https://github.com/moq/moq4/files/3480791/MoqDemo.zip)

**Comment by stakx** [comment]
>  If you required an example of the issue.

Thanks.

I've already added [these tests](https://github.com/moq/moq4/blob/86bab004196644e12e23aed0d6a717b108dea36c/tests/Moq.Tests/AfterReturnCallbackDelegateValidationFixture.cs) to Moq's test suite which cover the same use cases.

But I've quickly run your unit tests against Moq's `master`, and they now all fail... as they should.
