### ISSUE TITLE
Method without setup not return null

### ISSUE THREAD

**Issue by michelcedric** [moq/moq4#897]
Hi,
I make a MockTestCase project : https://github.com/michelcedric/MockTestCase/blob/master/MockTest/UnitTest1.cs

When a method without setup is defined normaly he returns null.
But If the return it's a IEnumerable, it's return an empty list.

I think it's a strange behavior and I don't understand why not return null?

Best regards

Cédric Michel

**Comment by stakx** [comment]
https://github.com/moq/moq4/blob/v4.12.0/CHANGELOG.md#changed:

> Setups with no `.Returns(…)` nor `.CallBase()` no longer return `default(T)` for loose mocks, but a value that is consistent with the mock's `CallBase` and `DefaultValue[Provider]` settings. (@stakx, #849)

(See also #877, of which this is a duplicate.)

**Comment by stakx** [comment]
Apologies, I misread your above post. This doesn't look like a duplicate.

**Comment by michelcedric** [comment]
Setups with no .Returns(…) nor .CallBase() no longer return default(T) for loose mocks, but a value that is consistent with the mock's CallBase and DefaultValue[Provider] settings. 

https://github.com/moq/moq4/issues/877
What do you hear by "but a value that is consistent with the mock's"?
Because in my test case if the return is a list it's return null but IEnumerable return an empty list,
And for me it's not consistent

**Comment by stakx** [comment]
> What do you hear by [...]

As per my last post, please ignore my initial statement, I was mistaken.

As to your unit tests, your tests fail due to two basic misunderstandings on your part:

* The `DateTime` test fails because the method you're setting up accepts a `DateTimeOffset`. While you are passing in `DateTime.Now`, that gets implicitly converted to `DateTimeOffset` by `DateTimeOffset`'s `implicit operator DateTimeOffset(DateTime)`. That's why your setup doesn't apply, a `DateTimeOffset` doesn't fulfill the `It.IsAny<DateTime>()` criterion.

* You may expect a `null` return value when calling a mocked method with a return type of `IEnumerable<>`, but Moq's `DefaultValue.Empty` strategy generates empty enumerables for such return types. That's been like that for many years now.

   If you want Moq to produce `null` for such methods, you can hook up a different `DefaultValueProvider`:

   ```csharp
   private class ZeroDefaultValueProvider : DefaultValueProvider
   {
       protected override object GetDefaultValue(Type type, Mock mock)
       {
           return type.IsValueType ? Activator.CreateInstance(type) : null;
       }
   }

   var mock = new Mock<T> { DefaultValueProvider = new ZeroDefaultValueProvider() };
   ...
   ```

**Comment by michelcedric** [comment]
```
var serviceMock = new Mock<IMeteringDataServiceAgent>();
serviceMock.Setup(s => s.GetDataList(It.IsAny<DateTime>())).Returns(_data);
var result3 = serviceMock.Object.GetDataList(new DateTime(2019,1,1));

//Expected the list but received null
//Because during the setup I put It.IsAny<DateTime>() and not It.IsAny<DateTimeOffset>()
Assert.AreEqual(_data, result3);
```
This unit test fail but in the setup I put DateTime and also during the invocation but it's fail?
It's because in my interface I defined a DateTimeOffset in parameter of GetDataList Method but why return null?

**Comment by stakx** [comment]
Like I already explained above: `GetDataList` never gets invoked with a `DateTime` but with a `DateTimeOffset`, therefore `It.IsAny<DateTime>()` doesn't match, therefore the whole setup including its `Returns` verb doesn't apply.

I suggest you read up on [user-defined conversion operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/user-defined-conversion-operators) and perhaps open up your code in a tool like ILDASM or ILSpy to see for yourself how `DateTime.Now` gets converted to a `DateTimeOffset`.

**Comment by michelcedric** [comment]
Why not raise an exception in this case instead of just return null?
Because Setup with It.IsAny<DateTime>() never working.
Best regards
Thanks

**Comment by stakx** [comment]
> Why not raise an exception in this case [...]?

*That* is a very valid question, and a good idea! Ideally, such situations would be flagged by a Roslyn analyzer, but since haven't (yet?) got one for Moq, we could try to produce a runtime error.
